android.useAndroidX=true
android.enableJetifier=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.builtInKotlin=false
android.newDsl=false
org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.caching=true
org.gradle.parallel=true
systemProp.file.encoding=utf-8
