org.gradle.jvmargs=-Xmx2048M --add-opens jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
systemProp.file.encoding=utf-8

android.useAndroidX=true
android.enableJetifier=true

# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true

# https://kotlinlang.org/docs/native-target-support.html
kotlin.native.ignoreDisabledTargets=true

# Workaround for INSTALL_BASELINE_PROFILE_FAILED
# This disables the baseline profile installation which fails when the package name suffix is used.
android.baselineprofile.skipgeneration=true
android.experimental.baseline-profile.enable-installation=false
android.baselineprofile.enable=false
android.enableBaselineProfile=false
