package org.schabi.newpipe.util

import android.content.Context
import org.schabi.newpipe.R
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.Stream
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream

object StreamLabelUtils {
    @JvmStatic
    fun getQualityLabel(context: Context, stream: Stream): String? = when (stream) {
        is VideoStream -> stream.resolution?.takeIf { it.isNotBlank() }
        is AudioStream -> {
            val bitrate = stream.averageBitrate
            if (bitrate > 0) "$bitrate kbps" else null
        }
        is SubtitlesStream -> {
            val language = stream.displayLanguageName
            if (language.isNullOrBlank()) {
                null
            } else if (stream.isAutoGenerated) {
                "$language (${context.getString(R.string.caption_auto_generated)})"
            } else {
                language
            }
        }
        else -> stream.format?.suffix?.takeIf { it.isNotBlank() }
    }
}
