package org.schabi.newpipe.util

import android.content.Context
import android.view.View
import android.view.ViewGroup
import android.widget.BaseAdapter
import android.widget.Spinner
import androidx.annotation.VisibleForTesting
import androidx.collection.SparseArrayCompat
import androidx.compose.ui.platform.ComposeView
import androidx.compose.ui.platform.ViewCompositionStrategy
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.schabi.newpipe.DownloaderImpl
import org.schabi.newpipe.R
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.downloader.Response
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.Stream
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream
import org.schabi.newpipe.extractor.utils.Utils
import org.schabi.newpipe.ui.components.StreamQualityItem
import us.shandian.giga.util.Utility
import java.io.Serializable
import java.util.Arrays
import java.util.Collections
import java.util.concurrent.Callable
import java.util.stream.Collectors

/**
 * A list adapter for a list of [Stream]s.
 * It currently supports [VideoStream], [AudioStream] and [SubtitlesStream].
 *
 * @param <T> the primary stream type's class extending [Stream]
 * @param <U> the secondary stream type's class extending [Stream]
 */
class StreamItemAdapter<T : Stream, U : Stream>(
    private val streamsWrapper: StreamInfoWrapper<T>,
    private val secondaryStreams: SparseArrayCompat<SecondaryStreamHelper<U>> = SparseArrayCompat(0)
) : BaseAdapter() {

    /**
     * Indicates that at least one of the primary streams is an instance of [VideoStream],
     * has no audio ([VideoStream.isVideoOnly] returns true) and has no secondary stream
     * associated with it.
     */
    private val hasAnyVideoOnlyStreamWithNoSecondaryStream: Boolean =
        checkHasAnyVideoOnlyStreamWithNoSecondaryStream()

    constructor(streamsWrapper: StreamInfoWrapper<T>) : this(streamsWrapper, SparseArrayCompat(0))

    fun getAll(): List<T> = streamsWrapper.streamsList

    fun getAllSecondary(): SparseArrayCompat<SecondaryStreamHelper<U>> = secondaryStreams

    override fun getCount(): Int = streamsWrapper.streamsList.size

    override fun getItem(position: Int): T = streamsWrapper.streamsList[position]

    override fun getItemId(position: Int): Long = position.toLong()

    override fun getDropDownView(position: Int, convertView: View?, parent: ViewGroup): View {
        return getCustomView(position, convertView, parent, true)
    }

    override fun getView(position: Int, convertView: View?, parent: ViewGroup): View {
        val selectedPosition = (parent as? Spinner)?.selectedItemPosition ?: position
        return getCustomView(selectedPosition, convertView, parent, false)
    }

    private fun getCustomView(
        position: Int,
        view: View?,
        parent: ViewGroup,
        isDropdownItem: Boolean
    ): View {
        val context = parent.context
        val composeView = (view as? ComposeView) ?: ComposeView(context).apply {
            setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnDetachedFromWindow)
        }

        val stream = getItem(position)
        val mediaFormat = streamsWrapper.getFormat(position)

        val woSoundIconVisibility: Int = if (stream is VideoStream && hasAnyVideoOnlyStreamWithNoSecondaryStream) {
            if (stream.isVideoOnly) {
                if (secondaryStreams.get(position) != null) {
                    if (isDropdownItem) View.INVISIBLE else View.GONE
                } else {
                    View.VISIBLE
                }
            } else if (isDropdownItem) {
                View.INVISIBLE
            } else {
                View.GONE
            }
        } else {
            View.GONE
        }

        val qualityString = when (stream) {
            is VideoStream -> stream.resolution
            is AudioStream -> {
                if (stream.averageBitrate > 0) {
                    "${stream.averageBitrate}kbps"
                } else {
                    context.getString(R.string.unknown_quality)
                }
            }
            is SubtitlesStream -> {
                var q = stream.displayLanguageName
                if (stream.isAutoGenerated) {
                    q += " (${context.getString(R.string.caption_auto_generated)})"
                }
                q
            }
            else -> mediaFormat?.suffix ?: context.getString(R.string.unknown_quality)
        }

        val sizeText: String? = if (streamsWrapper.getSizeInBytes(position) > 0) {
            val secondary = secondaryStreams.get(position)
            if (secondary != null) {
                Utility.formatBytes(secondary.sizeInBytes + streamsWrapper.getSizeInBytes(position))
            } else {
                streamsWrapper.getFormattedSize(position)
            }
        } else {
            null
        }

        val formatName = when (stream) {
            is SubtitlesStream -> stream.languageTag
            else -> when {
                mediaFormat == null -> context.getString(R.string.unknown_format)
                mediaFormat == MediaFormat.WEBMA_OPUS -> "opus"
                else -> mediaFormat.name
            }
        }

        composeView.setContent {
            StreamQualityItem(
                formatName = formatName,
                quality = qualityString,
                size = sizeText,
                isVideoOnly = woSoundIconVisibility != View.GONE,
                isIconVisible = woSoundIconVisibility == View.VISIBLE
            )
        }

        return composeView
    }

    private fun checkHasAnyVideoOnlyStreamWithNoSecondaryStream(): Boolean {
        for (i in streamsWrapper.streamsList.indices) {
            val stream = streamsWrapper.streamsList[i]
            if (stream is VideoStream && stream.isVideoOnly && secondaryStreams.get(i) == null) {
                return true
            }
        }
        return false
    }

    /**
     * A wrapper class that includes a way of storing the stream sizes.
     *
     * @param <T> the stream type's class extending [Stream]
     */
    class StreamInfoWrapper<T : Stream>(
        val streamsList: List<T>,
        context: Context?
    ) : Serializable {
        private val streamSizes: LongArray = LongArray(streamsList.size)
        private val streamFormats: Array<MediaFormat?> = arrayOfNulls(streamsList.size)
        private val unknownSize: String = context?.getString(R.string.unknown_content) ?: "--.-"

        init {
            resetInfo()
        }

        fun resetInfo() {
            Arrays.fill(streamSizes, SIZE_UNSET.toLong())
            for (i in streamsList.indices) {
                streamFormats[i] = streamsList[i]?.format
            }
        }

        fun getSizeInBytes(streamIndex: Int): Long = streamSizes[streamIndex]

        fun getSizeInBytes(stream: T): Long {
            val index = streamsList.indexOf(stream)
            return if (index != -1) streamSizes[index] else SIZE_UNSET.toLong()
        }

        fun getFormattedSize(streamIndex: Int): String = formatSize(getSizeInBytes(streamIndex))

        private fun formatSize(size: Long): String {
            return if (size > -1) {
                Utility.formatBytes(size)
            } else {
                unknownSize
            }
        }

        fun setSize(stream: T, sizeInBytes: Long) {
            val index = streamsList.indexOf(stream)
            if (index != -1) {
                streamSizes[index] = sizeInBytes
            }
        }

        fun getFormat(streamIndex: Int): MediaFormat? = streamFormats[streamIndex]

        fun setFormat(stream: T, format: MediaFormat) {
            val index = streamsList.indexOf(stream)
            if (index != -1) {
                streamFormats[index] = format
            }
        }

        companion object {
            private val EMPTY = StreamInfoWrapper<Stream>(Collections.emptyList(), null)
            private const val SIZE_UNSET = -2

            @JvmStatic
            fun <X : Stream> empty(): StreamInfoWrapper<X> = EMPTY as StreamInfoWrapper<X>

            /**
             * Helper method to fetch the sizes and missing media formats
             * of all the streams in a wrapper.
             */
            @JvmStatic
            suspend fun <X : Stream> fetchMoreInfoForWrapper(
                streamsWrapper: StreamInfoWrapper<X>
            ): Boolean = withContext(Dispatchers.IO) {
                try {
                    var hasChanged = false
                    for (stream in streamsWrapper.streamsList) {
                        val changeSize = streamsWrapper.getSizeInBytes(stream) <= SIZE_UNSET
                        val changeFormat = stream.format == null
                        if (!changeSize && !changeFormat) {
                            continue
                        }
                        val response = DownloaderImpl.instance?.head(stream.content) ?: return@withContext false
                        if (changeSize) {
                            val contentLength = response.getHeader("Content-Length")
                            if (!contentLength.isNullOrEmpty()) {
                                try {
                                    streamsWrapper.setSize(stream, contentLength.toLong())
                                    hasChanged = true
                                } catch (e: NumberFormatException) {
                                    // ignore
                                }
                            }
                        }
                        if (changeFormat) {
                            hasChanged = retrieveMediaFormat(stream, streamsWrapper, response) || hasChanged
                        }
                    }
                    hasChanged
                } catch (e: Exception) {
                    true
                }
            }

            @VisibleForTesting
            @JvmStatic
            fun <X : Stream> retrieveMediaFormat(
                stream: X,
                streamsWrapper: StreamInfoWrapper<X>,
                response: Response
            ): Boolean {
                return retrieveMediaFormatFromFileTypeHeaders(stream, streamsWrapper, response) ||
                        retrieveMediaFormatFromContentDispositionHeader(stream, streamsWrapper, response) ||
                        retrieveMediaFormatFromContentTypeHeader(stream, streamsWrapper, response)
            }

            @VisibleForTesting
            @JvmStatic
            fun <X : Stream> retrieveMediaFormatFromFileTypeHeaders(
                stream: X,
                streamsWrapper: StreamInfoWrapper<X>,
                response: Response
            ): Boolean {
                val keys = response.responseHeaders().keys.stream()
                    .filter { k: String -> k.endsWith("file-type") }
                    .collect(Collectors.toList())
                if (keys.isNotEmpty()) {
                    for (key in keys) {
                        val suffix = response.getHeader(key)
                        val format = MediaFormat.getFromSuffix(suffix)
                        if (format != null) {
                            streamsWrapper.setFormat(stream, format)
                            return true
                        }
                    }
                }
                return false
            }

            @VisibleForTesting
            @JvmStatic
            fun <X : Stream> retrieveMediaFormatFromContentDispositionHeader(
                stream: X,
                streamsWrapper: StreamInfoWrapper<X>,
                response: Response
            ): Boolean {
                var contentDisposition = response.getHeader("Content-Disposition") ?: return false
                try {
                    contentDisposition = Utils.decodeUrlUtf8(contentDisposition)
                    val parts = contentDisposition.split(";".toRegex()).toTypedArray()
                    for (part in parts) {
                        val p = part.trim { it <= ' ' }
                        val fileName: String
                        if (p.startsWith("filename=")) {
                            fileName = Utils.decodeUrlUtf8(p.substring(9))
                        } else if (p.startsWith("filename*=")) {
                            fileName = Utils.decodeUrlUtf8(p.substring(10))
                        } else {
                            continue
                        }
                        val splitFileName = fileName.split("\\.".toRegex()).toTypedArray()
                        var suffix = splitFileName[splitFileName.size - 1]
                        if (suffix.endsWith("\"") || suffix.endsWith("'")) {
                            suffix = suffix.substring(0, suffix.length - 1)
                        }
                        val format = MediaFormat.getFromSuffix(suffix)
                        if (format != null) {
                            streamsWrapper.setFormat(stream, format)
                            return true
                        }
                    }
                } catch (ignored: Exception) {
                }
                return false
            }

            @VisibleForTesting
            @JvmStatic
            fun <X : Stream> retrieveMediaFormatFromContentTypeHeader(
                stream: X,
                streamsWrapper: StreamInfoWrapper<X>,
                response: Response
            ): Boolean {
                val contentTypeHeader = response.getHeader("Content-Type") ?: return false
                var foundFormat: MediaFormat? = null
                for (format in MediaFormat.getAllFromMimeType(contentTypeHeader)) {
                    if (foundFormat == null) {
                        foundFormat = format
                    } else if (foundFormat.id != format.id) {
                        return false
                    }
                }
                if (foundFormat != null) {
                    streamsWrapper.setFormat(stream, foundFormat)
                    return true
                }
                return false
            }
        }
    }
}
