package org.schabi.newpipe.extractor.utils;

import javax.annotation.Nonnull;

/**
 * Describes the origin of a subtitle -> how its content was produced.
 *
 * - Currently, this enum covers YouTube subtitles, but
 *   it is designed to be extensible for other platforms
 *   (e.g. Peertube) in the future.
 */
public enum SubtitleOrigin {

    /**
     * Currently, YouTube subtitles are categorized
     * into three types:
     * - Subtitles manually uploaded by the video creator
     *   (HUMAN_PROVIDED).
     * - Subtitles automatically generated by YouTube's
     *   speech recognition (AUTO_GENERATED).
     * - Subtitles automatically translated by YouTube
     *   from an existing subtitle track (AUTO_TRANSLATED).
     */
    HUMAN_PROVIDED("human_provided"),
    AUTO_GENERATED("auto_generated"),
    AUTO_TRANSLATED("auto_translated");

    private final String id;

    SubtitleOrigin(@Nonnull final String id) {
        this.id = id;
    }

    @Nonnull
    public String getId() {
        return id;
    }
}
