package org.schabi.newpipe.streams;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import android.util.Log;

import org.schabi.newpipe.extractor.stream.StreamInfo;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;
import org.schabi.newpipe.extractor.MediaFormat;
import org.schabi.newpipe.util.subtitle.SubtitleDeduplicator;
import org.schabi.newpipe.util.subtitle.SubtitleOrigin;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class AppStreamInfo {
    private static final String TAG = AppStreamInfo.class.getSimpleName();

    @NonNull
    private final StreamInfo originalStreamInfo;
    @Nullable
    private List<SubtitlesStream> normalizedSubtitles = null;

    private AppStreamInfo(@NonNull final StreamInfo original) {
        this.originalStreamInfo = original;
    }

    // Factory method: build AppStreamInfo from raw StreamInfo.
    @NonNull
    public static AppStreamInfo from(@NonNull final StreamInfo info) {
        return new AppStreamInfo(info);
    }

    @NonNull
    public StreamInfo getOriginal() {
        return originalStreamInfo;
    }

    @NonNull
    public List<SubtitlesStream> loadNormalizedSubtitles() {
        if (null == normalizedSubtitles) {
            final List<SubtitlesStream> originalSubtitles =
                    originalStreamInfo.getSubtitles();

            normalizedSubtitles =
                    deduplicateSubtitles(originalSubtitles);
        }

        return normalizedSubtitles;
    }

    @NonNull
    private static List<SubtitlesStream> deduplicateSubtitles(
            @Nullable final List<SubtitlesStream> originalSubtitles) {

        if ((null == originalSubtitles) || originalSubtitles.isEmpty()) {
            return Collections.emptyList();
        }

        final List<SubtitlesStream> newSubtitles = new ArrayList<>();

        for (final SubtitlesStream oldSubtitle : originalSubtitles) {
            final MediaFormat format = oldSubtitle.getFormat();
            if (null == format) {
                newSubtitles.add(oldSubtitle);
                continue;
            }

            try {
                final SubtitleOrigin origin =
                        SubtitleDeduplicator.getSubtitleOrigin(
                            oldSubtitle.isAutoGenerated(),
                            false
                        );

                final String remoteSubtitleUrl = oldSubtitle.getContent();

                final String subtitleUrl =
                        SubtitleDeduplicator.checkAndDeduplicate(
                                remoteSubtitleUrl,
                                format,
                                origin
                        );

                if (remoteSubtitleUrl.equals(subtitleUrl)) {
                    newSubtitles.add(oldSubtitle);
                } else {
                    final SubtitlesStream oneNewSubtitle =
                        new SubtitlesStream.Builder()
                            .setContent(subtitleUrl, true)
                            .setMediaFormat(format)
                            .setLanguageCode(oldSubtitle.getLanguageTag())
                            .setAutoGenerated(oldSubtitle.isAutoGenerated())
                            .build();

                    newSubtitles.add(oneNewSubtitle);
                }
            } catch (final Exception e) {
                Log.w(TAG, "Subtitle deduplication failed", e);
                newSubtitles.add(oldSubtitle);
            }
        }

        return newSubtitles;
    }

}
