/**
 * Contains classes for searching inside the preferences.
 * <br></br>
 * This code is based on
 * [ByteHamster/SearchPreference](https://github.com/ByteHamster/SearchPreference)
 * (MIT license) but was heavily modified/refactored for our use.
 *
 * @author litetex
 */
package org.schabi.newpipe.settings.preferencesearch

import org.schabi.newpipe.error.ErrorPanelHelper.Companion.getExceptionDescription
import okhttp3.OkHttpClient.Builder.cache
import okhttp3.OkHttpClient.Builder.callTimeout
import okhttp3.OkHttpClient.Builder.build
import okhttp3.OkHttpClient.cache
import okhttp3.Cache.delete
import org.schabi.newpipe.util.SavedState.prefixFileSaved
import org.schabi.newpipe.util.SavedState.pathFileSaved
import org.schabi.newpipe.database.stream.dao.StreamDAO.upsert
import org.schabi.newpipe.error.ErrorUtil.Companion.createNotification
import org.schabi.newpipe.error.ErrorUtil.Companion.showUiErrorSnackbar
import org.schabi.newpipe.local.feed.FeedFragment.Companion.newInstance
import org.schabi.newpipe.error.ErrorInfo.messageStringId
import org.schabi.newpipe.error.ErrorInfo.stackTraces
import org.schabi.newpipe.error.ErrorInfo.userAction
import org.schabi.newpipe.error.ErrorInfo.request
import org.schabi.newpipe.error.ErrorInfo.serviceName
import org.schabi.newpipe.error.ErrorUtil.Companion.openActivity
import org.acra.data.CrashReportData.getString
import org.schabi.newpipe.database.stream.model.StreamEntity.url
import org.schabi.newpipe.database.stream.model.StreamEntity.uid
import org.schabi.newpipe.database.playlist.PlaylistStreamEntry.streamEntity
import org.schabi.newpipe.database.stream.model.StreamEntity.title
import org.schabi.newpipe.database.stream.model.StreamEntity.uploader
import org.schabi.newpipe.database.stream.model.StreamEntity.serviceId
import org.schabi.newpipe.database.stream.model.StreamEntity.duration
import org.schabi.newpipe.database.playlist.PlaylistStreamEntry.progressMillis
import org.schabi.newpipe.database.stream.model.StreamEntity.thumbnailUrl
import org.schabi.newpipe.ktx.animate
import org.schabi.newpipe.database.stream.StreamStatisticsEntry.watchCount
import org.schabi.newpipe.database.stream.StreamStatisticsEntry.latestAccessDate
import org.schabi.newpipe.database.stream.StreamStatisticsEntry.streamEntity
import org.schabi.newpipe.database.stream.StreamStatisticsEntry.progressMillis
import androidx.room.RoomDatabase.runInTransaction
import org.schabi.newpipe.database.history.model.SearchHistoryEntry.hasEqualValues
import org.schabi.newpipe.database.history.model.SearchHistoryEntry.creationDate
import org.schabi.newpipe.database.stream.dao.StreamDAO.getStream
import org.schabi.newpipe.database.stream.StreamStatisticsEntry.streamId
import org.schabi.newpipe.database.playlist.PlaylistStreamEntry.streamId
import org.schabi.newpipe.database.stream.StreamStatisticsEntry.toStreamInfoItem
import org.schabi.newpipe.database.stream.dao.StreamDAO.upsertAll
import org.schabi.newpipe.database.playlist.PlaylistStreamEntry.toStreamInfoItem
import org.schabi.newpipe.ktx.isNetworkRelated
import org.schabi.newpipe.local.subscription.SubscriptionManager.subscriptionTable
import org.schabi.newpipe.database.subscription.SubscriptionDAO.getAll
import org.schabi.newpipe.local.subscription.SubscriptionManager.upsertAll
import org.schabi.newpipe.error.ErrorUtil.Companion.showSnackbar
import org.schabi.newpipe.ktx.animateHideRecyclerViewAllowingScrolling
import org.schabi.newpipe.ktx.animateHeight
import org.schabi.newpipe.info_list.StreamSegmentAdapter.selectSegmentAt
import org.schabi.newpipe.info_list.StreamSegmentAdapter.setItems
import org.schabi.newpipe.info_list.StreamSegmentAdapter.selectSegment
import org.schabi.newpipe.views.player.PlayerFastSeekOverlay.seekSecondsSupplier
import org.schabi.newpipe.views.player.PlayerFastSeekOverlay.performListener
import org.schabi.newpipe.player.gesture.BasePlayerGestureListener.endMultiDoubleTap
import org.schabi.newpipe.player.gesture.BasePlayerGestureListener.keepInDoubleTapMode
import org.schabi.newpipe.player.gesture.BasePlayerGestureListener.doubleTapControls
import org.schabi.newpipe.ktx.animateRotation
import org.schabi.newpipe.player.gesture.BasePlayerGestureListener.isDoubleTapping
import org.schabi.newpipe.ktx.hasAssignableCause
import org.acra.ACRA.isACRASenderServiceProcess
import org.acra.config.CoreConfigurationBuilder.withBuildConfigClass
import org.acra.ACRA.init
import androidx.sqlite.db.SupportSQLiteDatabase.execSQL
import androidx.sqlite.db.SupportSQLiteDatabase.beginTransaction
import androidx.sqlite.db.SupportSQLiteDatabase.setTransactionSuccessful
import androidx.sqlite.db.SupportSQLiteDatabase.endTransaction
import com.jakewharton.rxbinding4.widget.textChanges
import org.schabi.newpipe.util.ReleaseVersionUtil.isReleaseApk
import org.schabi.newpipe.local.feed.notifications.NotificationWorker.Companion.runNow
import org.schabi.newpipe.local.subscription.SubscriptionManager.subscriptions
import org.schabi.newpipe.NewVersionWorker.Companion.enqueueNewVersionCheckingWork
import org.schabi.newpipe.settings.ContentSettingsManager.deleteSettingsFile
import org.schabi.newpipe.settings.ContentSettingsManager.exportDatabase
import org.schabi.newpipe.settings.ContentSettingsManager.ensureDbDirectoryExists
import org.schabi.newpipe.settings.ContentSettingsManager.extractDb
import org.schabi.newpipe.settings.ContentSettingsManager.extractSettings
import org.schabi.newpipe.settings.ContentSettingsManager.loadSharedPreferences
import org.schabi.newpipe.ktx.isInterruptedCaused
import org.schabi.newpipe.ktx.slideUp
import org.schabi.newpipe.database.subscription.SubscriptionDAO.getSubscriptionFlowable
import org.schabi.newpipe.local.feed.notifications.NotificationHelper.Companion.areNewStreamsNotificationsEnabled
import org.schabi.newpipe.local.subscription.SubscriptionManager.insertSubscription
import org.schabi.newpipe.local.subscription.SubscriptionManager.deleteSubscription
import org.schabi.newpipe.local.subscription.SubscriptionManager.updateChannelInfo
import com.jakewharton.rxbinding4.view.clicks
import org.schabi.newpipe.ktx.animateBackgroundColor
import org.schabi.newpipe.ktx.animateTextColor
import org.schabi.newpipe.local.subscription.SubscriptionManager.updateNotificationMode
import org.schabi.newpipe.error.ErrorPanelHelper.dispose
import org.schabi.newpipe.error.ErrorPanelHelper.showError
import org.schabi.newpipe.error.ErrorPanelHelper.showTextError
import org.schabi.newpipe.error.ErrorPanelHelper.hide
import org.schabi.newpipe.error.ErrorPanelHelper.isVisible
import org.schabi.newpipe.local.feed.notifications.NotificationWorker.Companion.initialize
import okhttp3.OkHttpClient.Builder.readTimeout
import okhttp3.Request.Builder.method
import okhttp3.Request.Builder.url
import okhttp3.Request.Builder.addHeader
import okhttp3.Request.Builder.removeHeader
import okhttp3.Request.Builder.header
import okhttp3.OkHttpClient.newCall
import okhttp3.Request.Builder.build
import okhttp3.Call.execute
import okhttp3.Response.close
import okhttp3.ResponseBody.string
import okhttp3.HttpUrl.toString
import okhttp3.Headers.toMultimap
import org.schabi.newpipe.error.ErrorInfo.throwable
import androidx.lifecycle.Lifecycle.currentState
import androidx.lifecycle.Lifecycle.State.isAtLeast
import androidx.lifecycle.Lifecycle.addObserver
import androidx.lifecycle.Lifecycle.removeObserver
import org.schabi.newpipe.util.urlfinder.UrlFinder.Companion.firstUrlFromInput
import androidx.room.Room.databaseBuilder
import androidx.room.RoomDatabase.Builder.addMigrations
import androidx.room.RoomDatabase.Builder.build
import androidx.room.RoomDatabase.query
import androidx.room.RoomDatabase.close
import us.shandian.giga.get.MissionRecoveryInfo.toString
import org.schabi.newpipe.error.ErrorInfo.Companion.throwableToStringList
import us.shandian.giga.get.MissionRecoveryInfo.validateCondition
import us.shandian.giga.get.MissionRecoveryInfo.kind
import us.shandian.giga.get.MissionRecoveryInfo.desiredBitrate
import us.shandian.giga.get.MissionRecoveryInfo.format
import us.shandian.giga.get.MissionRecoveryInfo.isDesired2
import us.shandian.giga.get.MissionRecoveryInfo.desired
import okio.ByteString.md5
import okio.ByteString.sha1
import okio.ByteString.hex
import androidx.viewpager.widget.PagerAdapter
import androidx.annotation.IntDef
import androidx.fragment.app.FragmentStatePagerAdapterMenuWorkaround
import android.view.ViewGroup
import android.os.Parcelable
import android.os.Bundle
import com.google.android.material.appbar.AppBarLayout
import org.schabi.newpipe.R
import androidx.coordinatorlayout.widget.CoordinatorLayout
import android.view.MotionEvent
import android.widget.OverScroller
import android.widget.TextView
import org.schabi.newpipe.util.text.LongPressLinkMovementMethod
import io.reactivex.rxjava3.disposables.CompositeDisposable
import org.schabi.newpipe.util.text.TextLinkifier
import androidx.core.text.HtmlCompat
import android.text.util.Linkify
import io.noties.markwon.Markwon
import io.noties.markwon.linkify.LinkifyPlugin
import io.reactivex.rxjava3.core.Single
import android.text.SpannableStringBuilder
import android.text.style.URLSpan
import org.schabi.newpipe.util.text.LongPressClickableSpan
import org.schabi.newpipe.util.text.UrlLongPressClickableSpan
import io.reactivex.rxjava3.android.schedulers.AndroidSchedulers
import org.schabi.newpipe.util.text.HashtagLongPressClickableSpan
import org.schabi.newpipe.util.text.TimestampExtractor
import org.schabi.newpipe.util.text.TimestampExtractor.TimestampMatchDTO
import org.schabi.newpipe.util.text.TimestampLongPressClickableSpan
import org.schabi.newpipe.util.text.TextEllipsizer
import org.schabi.newpipe.MainActivity
import org.schabi.newpipe.util.text.InternalUrlsHandler
import org.schabi.newpipe.extractor.StreamingService.LinkType
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.exceptions.ExtractionException
import org.schabi.newpipe.util.NavigationHelper
import org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.player.playqueue.PlayQueue
import org.schabi.newpipe.player.playqueue.SinglePlayQueue
import org.schabi.newpipe.error.ErrorPanelHelper
import android.text.style.ClickableSpan
import org.schabi.newpipe.util.external_communication.ShareUtils
import android.view.View.OnTouchListener
import android.annotation.SuppressLint
import android.text.Spanned
import org.schabi.newpipe.util.text.TouchUtils
import org.schabi.newpipe.util.text.CommentTextOnTouchListener
import android.text.method.LinkMovementMethod
import android.text.Spannable
import android.view.ViewConfiguration
import android.text.method.MovementMethod
import android.os.Looper
import org.schabi.newpipe.util.image.PreferredImageQuality
import org.schabi.newpipe.util.image.ImageStrategy
import org.schabi.newpipe.extractor.Image.ResolutionLevel
import okhttp3.OkHttpClient
import com.squareup.picasso.Picasso
import org.schabi.newpipe.util.image.PicassoHelper
import com.squareup.picasso.OkHttp3Downloader
import kotlin.Throws
import com.squareup.picasso.RequestCreator
import androidx.core.graphics.BitmapCompat
import androidx.annotation.DrawableRes
import org.schabi.newpipe.util.debounce.DebounceSavable
import io.reactivex.rxjava3.subjects.PublishSubject
import org.schabi.newpipe.util.debounce.DebounceSaver
import io.reactivex.rxjava3.disposables.Disposable
import org.schabi.newpipe.error.UserAction
import org.schabi.newpipe.util.InfoCache
import org.schabi.newpipe.util.ServiceHelper
import org.schabi.newpipe.util.ZipHelper
import org.schabi.newpipe.streams.io.StoredFileHelper
import org.schabi.newpipe.streams.io.SharpInputStream
import org.schabi.newpipe.extractor.stream.AudioTrackType
import org.schabi.newpipe.extractor.stream.VideoStream
import org.schabi.newpipe.extractor.stream.DeliveryMethod
import android.content.SharedPreferences
import androidx.annotation.StringRes
import android.net.ConnectivityManager
import androidx.core.content.ContextCompat
import org.schabi.newpipe.util.StateSaver
import android.text.TextUtils
import org.schabi.newpipe.util.StateSaver.WriteRead
import org.schabi.newpipe.util.DeviceUtils
import org.schabi.newpipe.App
import android.content.pm.PackageManager
import android.app.UiModeManager
import android.os.BatteryManager
import android.hardware.input.InputManager
import android.view.InputDevice
import androidx.appcompat.app.AppCompatActivity
import android.view.WindowManager
import android.view.WindowMetrics
import android.view.WindowInsets
import org.schabi.newpipe.util.ThemeHelper
import androidx.annotation.StyleRes
import androidx.annotation.AttrRes
import android.graphics.drawable.Drawable
import androidx.appcompat.content.res.AppCompatResources
import android.app.Activity
import androidx.appcompat.app.AppCompatDelegate
import org.schabi.newpipe.info_list.ItemViewMode
import android.widget.EditText
import org.ocpsoft.prettytime.PrettyTime
import org.schabi.newpipe.extractor.localization.ContentCountry
import org.schabi.newpipe.extractor.ListExtractor
import android.icu.text.CompactDecimalFormat
import org.ocpsoft.prettytime.units.Decade
import org.schabi.newpipe.extractor.localization.DateWrapper
import android.util.DisplayMetrics
import androidx.annotation.PluralsRes
import org.schabi.newpipe.util.FilenameUtils
import com.grack.nanojson.JsonObject
import com.grack.nanojson.JsonParser
import com.grack.nanojson.JsonParserException
import org.schabi.newpipe.extractor.services.peertube.PeertubeInstance
import androidx.recyclerview.widget.RecyclerView
import org.schabi.newpipe.util.PeertubeHelper
import com.grack.nanojson.JsonArray
import com.grack.nanojson.JsonStringWriter
import org.schabi.newpipe.util.SliderStrategy
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.util.StreamTypeUtil
import org.schabi.newpipe.util.SparseItemUtil
import android.widget.Toast
import io.reactivex.rxjava3.core.Completable
import org.schabi.newpipe.NewPipeDatabase
import org.schabi.newpipe.database.stream.model.StreamEntity
import org.schabi.newpipe.error.ErrorUtil
import org.schabi.newpipe.extractor.ListExtractor.InfoItemsPage
import org.schabi.newpipe.extractor.InfoItem
import org.schabi.newpipe.extractor.suggestion.SuggestionExtractor
import org.schabi.newpipe.extractor.channel.ChannelInfo
import org.schabi.newpipe.extractor.linkhandler.ListLinkHandler
import org.schabi.newpipe.extractor.channel.tabs.ChannelTabInfo
import org.schabi.newpipe.extractor.comments.CommentsInfo
import org.schabi.newpipe.extractor.comments.CommentsInfoItem
import org.schabi.newpipe.extractor.playlist.PlaylistInfo
import org.schabi.newpipe.extractor.kiosk.KioskInfo
import io.reactivex.rxjava3.core.Maybe
import io.reactivex.rxjava3.core.MaybeSource
import org.schabi.newpipe.extractor.MetaInfo
import org.schabi.newpipe.util.SerializedCache
import org.schabi.newpipe.extractor.channel.tabs.ChannelTabs
import org.schabi.newpipe.util.ChannelTabHelper
import android.content.Intent
import org.schabi.newpipe.player.PlayerType
import org.schabi.newpipe.player.playqueue.PlayQueueItem
import org.schabi.newpipe.util.PermissionHelper
import org.schabi.newpipe.player.PlayerService
import org.schabi.newpipe.player.helper.PlayerHolder
import android.content.DialogInterface
import org.schabi.newpipe.fragments.MainFragment
import org.schabi.newpipe.fragments.list.search.SearchFragment
import org.schabi.newpipe.fragments.detail.VideoDetailFragment
import org.schabi.newpipe.player.helper.PlayerHelper
import org.schabi.newpipe.util.NavigationHelper.RunnableWithVideoDetailFragment
import org.schabi.newpipe.fragments.list.channel.ChannelFragment
import androidx.fragment.app.FragmentActivity
import org.schabi.newpipe.fragments.list.comments.CommentRepliesFragment
import org.schabi.newpipe.fragments.list.playlist.PlaylistFragment
import kotlin.jvm.JvmOverloads
import org.schabi.newpipe.database.feed.model.FeedGroupEntity
import org.schabi.newpipe.local.feed.FeedFragment
import org.schabi.newpipe.local.bookmark.BookmarkFragment
import org.schabi.newpipe.local.subscription.SubscriptionFragment
import org.schabi.newpipe.fragments.list.kiosk.KioskFragment
import org.schabi.newpipe.local.playlist.LocalPlaylistFragment
import org.schabi.newpipe.local.history.StatisticsPlaylistFragment
import org.schabi.newpipe.local.subscription.SubscriptionsImportFragment
import org.schabi.newpipe.RouterActivity
import org.schabi.newpipe.about.AboutActivity
import org.schabi.newpipe.settings.SettingsActivity
import org.schabi.newpipe.download.DownloadActivity
import org.schabi.newpipe.player.PlayQueueActivity
import com.jakewharton.processphoenix.ProcessPhoenix
import org.schabi.newpipe.settings.NewPipeSettings
import androidx.core.app.ActivityCompat
import androidx.annotation.RequiresApi
import android.content.ActivityNotFoundException
import org.schabi.newpipe.fragments.list.playlist.PlaylistControlViewHolder
import org.schabi.newpipe.util.PlayButtonHelper
import android.view.View.OnLongClickListener
import org.schabi.newpipe.util.AudioTrackAdapter.AudioTracksWrapper
import android.widget.BaseAdapter
import android.view.LayoutInflater
import org.schabi.newpipe.util.StreamItemAdapter.StreamInfoWrapper
import androidx.collection.SparseArrayCompat
import org.schabi.newpipe.util.SecondaryStreamHelper
import android.widget.Spinner
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.DownloaderImpl
import org.schabi.newpipe.util.external_communication.KoreUtils
import android.content.pm.ResolveInfo
import android.content.ClipData
import androidx.core.content.FileProvider
import org.schabi.newpipe.util.NewPipeTextViewHelper
import com.nononsenseapps.filepicker.FilePickerActivity
import org.schabi.newpipe.util.FilePickerActivityHelper.CustomFilePickerFragment
import com.nononsenseapps.filepicker.AbstractFilePickerFragment
import android.os.Environment
import com.nononsenseapps.filepicker.FilePickerFragment
import androidx.recyclerview.widget.SortedList
import androidx.core.content.IntentCompat
import org.schabi.newpipe.error.ErrorActivity
import android.view.MenuInflater
import org.acra.sender.ReportSender
import org.acra.data.CrashReportData
import org.acra.ReportField
import org.schabi.newpipe.error.ReCaptchaActivity
import android.webkit.WebSettings
import android.webkit.WebViewClient
import android.webkit.WebView
import android.webkit.WebResourceRequest
import androidx.core.app.NavUtils
import com.google.auto.service.AutoService
import org.acra.sender.ReportSenderFactory
import org.acra.config.CoreConfiguration
import org.schabi.newpipe.error.AcraReportSender
import org.schabi.newpipe.local.dialog.PlaylistDialog
import org.schabi.newpipe.local.playlist.LocalPlaylistManager
import org.schabi.newpipe.local.dialog.PlaylistAppendDialog
import org.schabi.newpipe.local.dialog.PlaylistCreationDialog
import org.schabi.newpipe.local.LocalItemListAdapter
import org.schabi.newpipe.util.OnClickGesture
import org.schabi.newpipe.database.playlist.PlaylistDuplicatesEntry
import androidx.recyclerview.widget.LinearLayoutManager
import org.schabi.newpipe.database.playlist.model.PlaylistEntity
import android.text.InputType
import org.schabi.newpipe.local.LocalItemBuilder
import org.schabi.newpipe.local.history.HistoryRecordManager
import org.schabi.newpipe.local.holder.LocalItemHolder
import org.schabi.newpipe.local.holder.PlaylistItemHolder
import org.schabi.newpipe.database.playlist.PlaylistMetadataEntry
import org.schabi.newpipe.local.holder.LocalPlaylistItemHolder
import org.schabi.newpipe.database.playlist.model.PlaylistRemoteEntity
import org.schabi.newpipe.local.holder.RemotePlaylistItemHolder
import org.schabi.newpipe.views.AnimatedProgressBar
import org.schabi.newpipe.database.playlist.PlaylistStreamEntry
import org.schabi.newpipe.util.DependentPreferenceHelper
import org.schabi.newpipe.database.stream.StreamStatisticsEntry
import org.schabi.newpipe.local.holder.LocalPlaylistStreamItemHolder
import org.schabi.newpipe.local.holder.LocalStatisticStreamItemHolder
import org.schabi.newpipe.local.history.HistoryEntryAdapter.OnHistoryItemClickListener
import org.schabi.newpipe.database.AppDatabase
import org.schabi.newpipe.database.stream.dao.StreamDAO
import org.schabi.newpipe.database.history.dao.StreamHistoryDAO
import org.schabi.newpipe.database.history.dao.SearchHistoryDAO
import org.schabi.newpipe.database.stream.dao.StreamStateDAO
import org.schabi.newpipe.database.stream.model.StreamStateEntity
import org.schabi.newpipe.database.history.model.StreamHistoryEntity
import io.reactivex.rxjava3.core.Flowable
import org.schabi.newpipe.database.history.model.StreamHistoryEntry
import org.schabi.newpipe.database.history.model.SearchHistoryEntry
import org.schabi.newpipe.database.playlist.model.PlaylistStreamEntity
import org.schabi.newpipe.local.BaseLocalListFragment
import org.schabi.newpipe.local.history.StatisticsPlaylistFragment.StatisticSortMode
import androidx.viewbinding.ViewBinding
import org.schabi.newpipe.settings.HistorySettingsFragment
import org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry
import org.schabi.newpipe.info_list.dialog.StreamDialogEntry.StreamDialogEntryAction
import com.google.android.material.snackbar.Snackbar
import org.schabi.newpipe.database.playlist.PlaylistLocalItem
import org.schabi.newpipe.local.playlist.RemotePlaylistManager
import androidx.recyclerview.widget.ItemTouchHelper
import org.schabi.newpipe.database.LocalItem.LocalItemType
import org.schabi.newpipe.local.bookmark.MergedPlaylistManager
import org.schabi.newpipe.BaseFragment
import org.schabi.newpipe.local.holder.LocalBookmarkPlaylistItemHolder
import org.schabi.newpipe.local.holder.RemoteBookmarkPlaylistItemHolder
import org.schabi.newpipe.database.playlist.dao.PlaylistDAO
import org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO
import org.schabi.newpipe.fragments.MainFragment.SelectedTabsPagerAdapter
import io.reactivex.rxjava3.core.SingleSource
import org.schabi.newpipe.database.playlist.dao.PlaylistRemoteDAO
import org.schabi.newpipe.extractor.subscription.SubscriptionExtractor.InvalidSourceException
import org.schabi.newpipe.local.subscription.services.ImportExportEventListener
import org.schabi.newpipe.local.subscription.services.ImportExportJsonHelper
import com.grack.nanojson.JsonAppendableWriter
import io.reactivex.rxjava3.processors.PublishProcessor
import androidx.core.app.NotificationManagerCompat
import android.os.IBinder
import org.schabi.newpipe.local.subscription.services.BaseImportExportService
import androidx.core.app.ServiceCompat
import org.schabi.newpipe.local.subscription.services.SubscriptionsExportService
import org.schabi.newpipe.streams.io.SharpOutputStream
import org.schabi.newpipe.database.subscription.SubscriptionEntity
import androidx.localbroadcastmanager.content.LocalBroadcastManager
import org.schabi.newpipe.local.subscription.services.SubscriptionsImportService
import icepick.Icepick
import org.schabi.newpipe.local.subscription.ImportConfirmationDialog
import org.schabi.newpipe.extractor.subscription.SubscriptionExtractor.ContentSource
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.ActivityResultCallback
import org.schabi.newpipe.streams.io.NoFileManagerSafeGuard
import org.schabi.newpipe.extractor.subscription.SubscriptionExtractor
import androidx.core.text.util.LinkifyCompat
import org.schabi.newpipe.local.HeaderFooterHolder
import org.schabi.newpipe.local.holder.LocalPlaylistGridItemHolder
import org.schabi.newpipe.local.holder.LocalPlaylistCardItemHolder
import org.schabi.newpipe.local.holder.RemotePlaylistGridItemHolder
import org.schabi.newpipe.local.holder.RemotePlaylistCardItemHolder
import org.schabi.newpipe.local.holder.LocalPlaylistStreamGridItemHolder
import org.schabi.newpipe.local.holder.LocalPlaylistStreamCardItemHolder
import org.schabi.newpipe.local.holder.LocalStatisticStreamGridItemHolder
import org.schabi.newpipe.local.holder.LocalStatisticStreamCardItemHolder
import org.schabi.newpipe.util.FallbackViewHolder
import androidx.recyclerview.widget.GridLayoutManager.SpanSizeLookup
import org.schabi.newpipe.fragments.BaseStateFragment
import org.schabi.newpipe.fragments.list.ListViewContract
import android.content.SharedPreferences.OnSharedPreferenceChangeListener
import androidx.recyclerview.widget.GridLayoutManager
import android.widget.LinearLayout
import org.schabi.newpipe.views.CollapsibleView.ViewMode
import org.schabi.newpipe.views.CollapsibleView
import android.animation.ValueAnimator
import org.schabi.newpipe.views.CollapsibleView.StateListener
import android.view.View.MeasureSpec
import androidx.appcompat.widget.AppCompatEditText
import androidx.appcompat.widget.AppCompatTextView
import android.widget.TextView.BufferType
import android.view.ViewTreeObserver.OnGlobalFocusChangeListener
import android.view.ViewTreeObserver.OnDrawListener
import android.view.ViewTreeObserver.OnGlobalLayoutListener
import android.view.ViewTreeObserver.OnScrollChangedListener
import android.view.ViewTreeObserver.OnTouchModeChangeListener
import android.graphics.PixelFormat
import android.graphics.ColorFilter
import org.schabi.newpipe.views.FocusOverlayView
import android.view.ViewTreeObserver
import androidx.appcompat.view.WindowCallbackWrapper
import androidx.appcompat.widget.AppCompatSeekBar
import org.schabi.newpipe.views.FocusAwareSeekBar.NestedListener
import android.widget.SeekBar.OnSeekBarChangeListener
import android.widget.SeekBar
import android.widget.ProgressBar
import org.schabi.newpipe.views.AnimatedProgressBar.ProgressBarAnimation
import android.view.animation.Animation
import android.view.animation.AccelerateDecelerateInterpolator
import org.schabi.newpipe.views.NewPipeRecyclerView
import android.view.FocusFinder
import com.google.android.material.tabs.TabLayout
import org.schabi.newpipe.views.ScrollableTabLayout
import android.view.SurfaceView
import com.google.android.exoplayer2.ui.AspectRatioFrameLayout
import com.google.android.exoplayer2.ui.AspectRatioFrameLayout.ResizeMode
import androidx.core.view.WindowInsetsCompat
import androidx.drawerlayout.widget.DrawerLayout
import com.google.android.material.appbar.CollapsingToolbarLayout
import androidx.core.view.ViewCompat
import com.google.android.exoplayer2.Tracks
import com.google.android.exoplayer2.PlaybackParameters
import com.google.android.exoplayer2.text.Cue
import com.google.android.exoplayer2.video.VideoSize
import org.schabi.newpipe.player.ui.VideoPlayerUi
import android.view.View.OnLayoutChangeListener
import android.database.ContentObserver
import org.schabi.newpipe.player.playqueue.PlayQueueAdapter
import org.schabi.newpipe.info_list.StreamSegmentAdapter
import org.schabi.newpipe.player.event.PlayerServiceEventListener
import org.schabi.newpipe.player.gesture.BasePlayerGestureListener
import org.schabi.newpipe.player.gesture.MainPlayerGestureListener
import android.view.ViewParent
import android.widget.FrameLayout
import org.schabi.newpipe.player.notification.NotificationConstants
import org.schabi.newpipe.player.helper.PlayerHelper.MinimizeMode
import org.schabi.newpipe.extractor.stream.StreamSegment
import org.schabi.newpipe.player.ui.MainPlayerUi
import org.schabi.newpipe.ktx.AnimationType
import org.schabi.newpipe.fragments.OnScrollBelowItemsListener
import org.schabi.newpipe.info_list.StreamSegmentAdapter.StreamSegmentListener
import org.schabi.newpipe.info_list.StreamSegmentItem
import org.schabi.newpipe.player.mediaitem.MediaItemTag
import org.schabi.newpipe.player.playqueue.PlayQueueItemTouchCallback
import org.schabi.newpipe.QueueItemMenuUtil
import org.schabi.newpipe.player.playqueue.PlayQueueItemHolder
import org.schabi.newpipe.player.helper.PlaybackParameterDialog
import org.schabi.newpipe.player.ui.PlayerUi
import org.schabi.newpipe.player.gesture.PopupPlayerGestureListener
import org.schabi.newpipe.player.ui.PopupPlayerUi
import android.view.animation.AnticipateInterpolator
import android.animation.AnimatorListenerAdapter
import com.google.android.exoplayer2.ui.SubtitleView
import android.view.Gravity
import org.schabi.newpipe.player.playback.SurfaceHolderCallback
import android.view.GestureDetector
import org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHolder
import android.graphics.PorterDuffColorFilter
import android.graphics.PorterDuff
import android.widget.RelativeLayout
import org.schabi.newpipe.views.player.PlayerFastSeekOverlay.PerformListener
import org.schabi.newpipe.player.gesture.DisplayPortion
import org.schabi.newpipe.views.player.PlayerFastSeekOverlay.PerformListener.FastSeekDirection
import org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHelper
import org.schabi.newpipe.player.ui.VideoPlayerUi.PlayButtonAction
import androidx.appcompat.widget.AppCompatImageButton
import com.google.android.exoplayer2.C
import com.google.android.exoplayer2.source.TrackGroup
import com.google.android.exoplayer2.ui.CaptionStyleCompat
import com.google.android.exoplayer2.ExoPlayer
import org.schabi.newpipe.player.event.PlayerEventListener
import com.google.android.exoplayer2.PlaybackException
import android.os.PowerManager
import android.net.wifi.WifiManager
import android.os.PowerManager.WakeLock
import android.net.wifi.WifiManager.WifiLock
import android.media.AudioManager.OnAudioFocusChangeListener
import com.google.android.exoplayer2.analytics.AnalyticsListener
import android.media.AudioManager
import androidx.media.AudioFocusRequestCompat
import org.schabi.newpipe.player.helper.AudioReactor
import androidx.media.AudioManagerCompat
import android.animation.ValueAnimator.AnimatorUpdateListener
import com.google.android.exoplayer2.analytics.AnalyticsListener.EventTime
import android.media.audiofx.AudioEffect
import com.google.android.exoplayer2.upstream.TransferListener
import com.google.android.exoplayer2.upstream.cache.SimpleCache
import com.google.android.exoplayer2.upstream.DefaultDataSource
import com.google.android.exoplayer2.upstream.FileDataSource
import com.google.android.exoplayer2.upstream.cache.CacheDataSink
import com.google.android.exoplayer2.upstream.cache.CacheDataSource
import org.schabi.newpipe.player.helper.CacheFactory
import com.google.android.exoplayer2.util.MimeTypes
import org.schabi.newpipe.player.helper.PlayerHelper.AutoplayType
import com.google.android.exoplayer2.SeekParameters
import com.google.android.exoplayer2.trackselection.ExoTrackSelection
import com.google.android.exoplayer2.trackselection.AdaptiveTrackSelection
import android.view.accessibility.CaptioningManager
import com.google.android.exoplayer2.source.ProgressiveMediaSource
import org.schabi.newpipe.player.event.PlayerServiceExtendedEventListener
import org.schabi.newpipe.player.helper.PlayerHolder.PlayerServiceConnection
import android.content.ServiceConnection
import android.content.ComponentName
import org.schabi.newpipe.player.PlayerService.LocalBinder
import com.google.android.exoplayer2.DefaultLoadControl
import org.schabi.newpipe.player.helper.PlayerDataSource
import com.google.android.exoplayer2.upstream.DefaultHttpDataSource
import org.schabi.newpipe.extractor.services.youtube.dashmanifestcreators.YoutubeProgressiveDashManifestCreator
import org.schabi.newpipe.extractor.services.youtube.dashmanifestcreators.YoutubeOtfDashManifestCreator
import org.schabi.newpipe.extractor.services.youtube.dashmanifestcreators.YoutubePostLiveStreamDvrDashManifestCreator
import com.google.android.exoplayer2.source.smoothstreaming.SsMediaSource
import com.google.android.exoplayer2.source.hls.HlsMediaSource
import com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistTracker
import com.google.android.exoplayer2.source.hls.HlsDataSourceFactory
import com.google.android.exoplayer2.upstream.LoadErrorHandlingPolicy
import com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParserFactory
import com.google.android.exoplayer2.source.hls.playlist.DefaultHlsPlaylistTracker
import com.google.android.exoplayer2.source.dash.DashMediaSource
import com.google.android.exoplayer2.source.smoothstreaming.DefaultSsChunkSource
import com.google.android.exoplayer2.source.SingleSampleMediaSource
import com.google.android.exoplayer2.source.dash.DefaultDashChunkSource
import com.google.android.exoplayer2.upstream.cache.LeastRecentlyUsedCacheEvictor
import com.google.android.exoplayer2.database.StandaloneDatabaseProvider
import org.schabi.newpipe.player.helper.PlayerSemitoneHelper
import com.google.android.exoplayer2.DefaultRenderersFactory
import com.google.android.exoplayer2.DefaultRenderersFactory.ExtensionRendererMode
import com.google.android.exoplayer2.mediacodec.MediaCodecSelector
import com.google.android.exoplayer2.video.VideoRendererEventListener
import org.schabi.newpipe.player.helper.CustomMediaCodecVideoRenderer
import android.widget.CompoundButton
import android.graphics.drawable.LayerDrawable
import android.widget.CheckBox
import org.schabi.newpipe.util.SimpleOnSeekBarChangeListener
import org.schabi.newpipe.util.SliderStrategy.Quadratic
import com.google.android.exoplayer2.mediacodec.MediaCodecAdapter
import com.google.android.exoplayer2.video.MediaCodecVideoRenderer
import com.google.android.material.bottomsheet.BottomSheetBehavior
import com.google.android.exoplayer2.source.MediaSource
import org.schabi.newpipe.player.playback.PlaybackListener
import org.schabi.newpipe.player.mediasource.ManagedMediaSourcePlaylist
import io.reactivex.rxjava3.internal.subscriptions.EmptySubscription
import org.schabi.newpipe.player.playqueue.events.PlayQueueEvent
import org.schabi.newpipe.player.playqueue.events.PlayQueueEventType
import org.schabi.newpipe.player.playqueue.events.RemoveEvent
import org.schabi.newpipe.player.playqueue.events.MoveEvent
import org.schabi.newpipe.player.playqueue.events.ReorderEvent
import org.schabi.newpipe.player.playback.MediaSourceManager
import org.schabi.newpipe.player.mediasource.ManagedMediaSource
import org.schabi.newpipe.player.playback.MediaSourceManager.ItemsToLoad
import org.schabi.newpipe.player.mediasource.LoadedMediaSource
import org.schabi.newpipe.player.mediasource.FailedMediaSource
import org.schabi.newpipe.player.mediasource.FailedMediaSource.MediaSourceResolutionException
import org.schabi.newpipe.player.mediasource.FailedMediaSource.StreamInfoLoadException
import android.view.SurfaceHolder
import com.google.android.exoplayer2.video.PlaceholderSurface
import org.schabi.newpipe.player.resolver.PlaybackResolver
import org.schabi.newpipe.player.mediaitem.StreamInfoTag
import org.schabi.newpipe.player.resolver.PlaybackResolver.ResolverException
import com.google.android.exoplayer2.MediaItem.LiveConfiguration
import com.google.android.exoplayer2.source.dash.manifest.DashManifest
import com.google.android.exoplayer2.source.dash.manifest.DashManifestParser
import com.google.android.exoplayer2.source.smoothstreaming.manifest.SsManifest
import com.google.android.exoplayer2.source.smoothstreaming.manifest.SsManifestParser
import org.schabi.newpipe.extractor.services.youtube.ItagItem
import org.schabi.newpipe.extractor.services.youtube.dashmanifestcreators.CreationException
import org.schabi.newpipe.player.resolver.AudioPlaybackResolver
import org.schabi.newpipe.player.resolver.VideoPlaybackResolver.QualityResolver
import org.schabi.newpipe.player.resolver.VideoPlaybackResolver.SourceType
import org.schabi.newpipe.player.resolver.VideoPlaybackResolver
import com.google.android.exoplayer2.C.RoleFlags
import com.google.android.exoplayer2.MediaItem.SubtitleConfiguration
import com.google.android.exoplayer2.source.MergingMediaSource
import org.schabi.newpipe.player.mediaitem.ExceptionTag
import com.google.android.exoplayer2.MediaItem.RequestMetadata
import com.google.android.exoplayer2.MediaItem.LocalConfiguration
import org.schabi.newpipe.player.mediaitem.PlaceholderTag
import io.reactivex.rxjava3.subjects.BehaviorSubject
import io.reactivex.rxjava3.core.BackpressureStrategy
import org.schabi.newpipe.player.playqueue.events.InitEvent
import org.schabi.newpipe.player.playqueue.events.SelectEvent
import org.schabi.newpipe.player.playqueue.events.AppendEvent
import org.schabi.newpipe.player.playqueue.events.ErrorEvent
import org.schabi.newpipe.player.playqueue.events.RecoveryEvent
import org.schabi.newpipe.player.playqueue.PlayQueueItemBuilder
import org.schabi.newpipe.player.playqueue.AbstractInfoPlayQueue
import org.schabi.newpipe.extractor.ListInfo
import io.reactivex.rxjava3.core.SingleObserver
import com.google.android.exoplayer2.upstream.HttpDataSource.RequestProperties
import com.google.android.exoplayer2.upstream.BaseDataSource
import com.google.android.exoplayer2.upstream.HttpDataSource
import org.schabi.newpipe.player.datasource.YoutubeHttpDataSource
import com.google.android.exoplayer2.upstream.DataSpec
import com.google.android.exoplayer2.upstream.HttpDataSource.HttpDataSourceException
import com.google.android.exoplayer2.upstream.HttpUtil
import com.google.android.exoplayer2.upstream.DataSourceException
import com.google.android.exoplayer2.upstream.HttpDataSource.InvalidResponseCodeException
import com.google.android.exoplayer2.upstream.HttpDataSource.InvalidContentTypeException
import org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper
import org.schabi.newpipe.player.datasource.NonUriHlsDataSourceFactory
import com.google.android.exoplayer2.upstream.ByteArrayDataSource
import com.google.android.exoplayer2.trackselection.DefaultTrackSelector
import org.schabi.newpipe.player.helper.LoadController
import org.schabi.newpipe.player.ui.PlayerUiList
import android.content.IntentFilter
import io.reactivex.rxjava3.disposables.SerialDisposable
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter
import org.schabi.newpipe.player.helper.CustomRenderersFactory
import org.schabi.newpipe.player.mediasession.MediaSessionPlayerUi
import org.schabi.newpipe.player.notification.NotificationPlayerUi
import com.squareup.picasso.Picasso.LoadedFrom
import com.google.android.exoplayer2.Player.PositionInfo
import com.google.android.exoplayer2.Player.DiscontinuityReason
import com.google.android.exoplayer2.text.CueGroup
import com.google.android.exoplayer2.Timeline
import com.google.android.exoplayer2.trackselection.MappingTrackSelector.MappedTrackInfo
import com.google.android.exoplayer2.source.BaseMediaSource
import org.schabi.newpipe.player.mediasource.FailedMediaSource.FailedMediaSourceException
import com.google.android.exoplayer2.upstream.Allocator
import com.google.android.exoplayer2.source.MediaPeriod
import com.google.android.exoplayer2.source.SinglePeriodTimeline
import com.google.android.exoplayer2.source.SilenceMediaSource
import com.google.android.exoplayer2.source.WrappingMediaSource
import com.google.android.exoplayer2.source.CompositeMediaSource
import org.schabi.newpipe.player.mediasource.PlaceholderMediaSource
import com.google.android.exoplayer2.source.ConcatenatingMediaSource
import com.google.android.exoplayer2.source.ShuffleOrder.UnshuffledShuffleOrder
import android.support.v4.media.session.MediaSessionCompat
import com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.QueueNavigator
import android.support.v4.media.session.PlaybackStateCompat
import org.schabi.newpipe.player.mediasession.PlayQueueNavigator
import android.support.v4.media.MediaDescriptionCompat
import android.support.v4.media.MediaMetadataCompat
import com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector
import org.schabi.newpipe.player.notification.NotificationActionData
import com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.MediaButtonEventHandler
import com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.MediaMetadataProvider
import androidx.media.session.MediaButtonReceiver
import com.google.android.exoplayer2.ForwardingPlayer
import org.schabi.newpipe.player.mediasession.SessionConnectorActionProvider
import com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.CustomActionProvider
import androidx.core.app.PendingIntentCompat
import android.app.PendingIntent
import org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHelper.SeekbarPreviewThumbnailType
import org.schabi.newpipe.extractor.stream.Frameset
import org.schabi.newpipe.player.AudioServiceLeakFix
import android.widget.ImageButton
import android.view.SubMenu
import android.content.ContextWrapper
import org.schabi.newpipe.streams.io.SharpStream
import androidx.documentfile.provider.DocumentFile
import org.schabi.newpipe.util.FilePickerActivityHelper
import android.content.ContentResolver
import us.shandian.giga.io.FileStream
import us.shandian.giga.io.FileStreamSAF
import android.provider.DocumentsContract
import org.schabi.newpipe.streams.io.StoredDirectoryHelper
import com.nononsenseapps.filepicker.AbstractFilePickerActivity
import android.os.storage.StorageManager
import android.os.storage.StorageVolume
import org.schabi.newpipe.streams.WebMReader.WebMTrack
import org.schabi.newpipe.streams.WebMReader
import org.schabi.newpipe.streams.WebMReader.SimpleBlock
import org.schabi.newpipe.streams.WebMReader.Cluster
import org.schabi.newpipe.streams.WebMWriter.ClusterInfo
import org.schabi.newpipe.streams.WebMWriter
import org.schabi.newpipe.streams.WebMWriter.KeyFrame
import org.schabi.newpipe.streams.Mp4DashReader.Moof
import org.schabi.newpipe.streams.Mp4DashReader
import org.schabi.newpipe.streams.Mp4DashReader.Moov
import org.schabi.newpipe.streams.Mp4DashReader.Trex
import org.schabi.newpipe.streams.Mp4DashReader.Mp4DashChunk
import org.schabi.newpipe.streams.Mp4DashReader.Traf
import org.schabi.newpipe.streams.Mp4DashReader.Tfhd
import org.schabi.newpipe.streams.Mp4DashReader.Trun
import org.schabi.newpipe.streams.Mp4DashReader.TrunEntry
import org.schabi.newpipe.streams.Mp4DashReader.Mvhd
import org.schabi.newpipe.streams.Mp4DashReader.Tkhd
import org.schabi.newpipe.streams.Mp4DashReader.Trak
import org.schabi.newpipe.streams.Mp4DashReader.Mdia
import org.schabi.newpipe.streams.Mp4DashReader.Hdlr
import org.schabi.newpipe.streams.Mp4DashReader.Elst
import org.schabi.newpipe.streams.Mp4DashReader.Minf
import org.schabi.newpipe.streams.Mp4DashReader.Mp4DashSample
import org.schabi.newpipe.streams.Mp4FromDashWriter
import org.schabi.newpipe.streams.Mp4FromDashWriter.TablesInfo
import org.schabi.newpipe.streams.OggFromWebMWriter
import org.schabi.newpipe.streams.SrtFromTtmlWriter
import org.jsoup.Jsoup
import org.jsoup.nodes.TextNode
import io.reactivex.rxjava3.plugins.RxJavaPlugins
import io.reactivex.rxjava3.exceptions.UndeliverableException
import io.reactivex.rxjava3.exceptions.CompositeException
import io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException
import io.reactivex.rxjava3.exceptions.MissingBackpressureException
import org.acra.config.CoreConfigurationBuilder
import androidx.core.app.NotificationChannelCompat
import androidx.room.Dao
import org.schabi.newpipe.database.BasicDAO
import androidx.room.OnConflictStrategy
import androidx.room.ColumnInfo
import org.schabi.newpipe.database.history.dao.HistoryDAO
import androidx.room.RewriteQueriesToDropUnusedColumns
import androidx.room.PrimaryKey
import org.schabi.newpipe.database.subscription.NotificationMode
import org.schabi.newpipe.extractor.channel.ChannelInfoItem
import androidx.room.Delete
import org.schabi.newpipe.database.Migrations
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.room.TypeConverters
import org.schabi.newpipe.database.Converters
import org.schabi.newpipe.database.feed.model.FeedEntity
import org.schabi.newpipe.database.feed.model.FeedGroupSubscriptionEntity
import org.schabi.newpipe.database.feed.model.FeedLastUpdatedEntity
import androidx.room.RoomDatabase
import org.schabi.newpipe.database.feed.dao.FeedDAO
import org.schabi.newpipe.database.feed.dao.FeedGroupDAO
import org.schabi.newpipe.database.subscription.SubscriptionDAO
import org.schabi.newpipe.download.LoadingDialog
import android.widget.RadioGroup
import android.widget.AdapterView
import androidx.appcompat.view.menu.ActionMenuItemView
import org.schabi.newpipe.util.AudioTrackAdapter
import org.schabi.newpipe.util.StreamItemAdapter
import org.schabi.newpipe.download.DownloadDialog
import us.shandian.giga.service.DownloadManagerService
import us.shandian.giga.service.DownloadManagerService.DownloadManagerBinder
import androidx.annotation.IdRes
import android.text.Editable
import us.shandian.giga.service.MissionState
import us.shandian.giga.get.MissionRecoveryInfo
import us.shandian.giga.postprocessing.Postprocessing
import us.shandian.giga.ui.fragment.MissionsFragment
import org.schabi.newpipe.settings.tabs.Tab.BlankTab
import org.schabi.newpipe.settings.tabs.Tab.DefaultKioskTab
import org.schabi.newpipe.settings.tabs.Tab.SubscriptionsTab
import org.schabi.newpipe.settings.tabs.Tab.FeedTab
import org.schabi.newpipe.settings.tabs.Tab.BookmarksTab
import org.schabi.newpipe.settings.tabs.Tab.HistoryTab
import org.schabi.newpipe.settings.tabs.Tab.KioskTab
import org.schabi.newpipe.settings.tabs.Tab.ChannelTab
import org.schabi.newpipe.settings.tabs.Tab.PlaylistTab
import org.schabi.newpipe.fragments.BlankFragment
import org.schabi.newpipe.util.KioskTranslator
import org.schabi.newpipe.fragments.list.kiosk.DefaultKioskFragment
import org.schabi.newpipe.settings.tabs.TabsManager.SavedTabsChangeListener
import org.schabi.newpipe.settings.tabs.TabsJsonHelper
import org.schabi.newpipe.settings.tabs.TabsJsonHelper.InvalidJsonException
import org.schabi.newpipe.settings.tabs.TabsManager
import org.schabi.newpipe.settings.tabs.AddTabDialog.ChooseTabListItem
import org.schabi.newpipe.settings.tabs.AddTabDialog.DialogListAdapter
import androidx.appcompat.widget.AppCompatImageView
import org.schabi.newpipe.settings.tabs.ChooseTabsFragment.SelectedTabsAdapter
import com.google.android.material.floatingactionbutton.FloatingActionButton
import org.schabi.newpipe.settings.tabs.AddTabDialog
import org.schabi.newpipe.settings.SelectKioskFragment
import org.schabi.newpipe.settings.SelectChannelFragment
import org.schabi.newpipe.settings.SelectPlaylistFragment
import org.schabi.newpipe.settings.custom.NotificationSlot
import android.widget.RadioButton
import android.content.res.ColorStateList
import androidx.core.widget.TextViewCompat
import org.schabi.newpipe.settings.preferencesearch.PreferenceSearchConfiguration
import androidx.annotation.XmlRes
import org.schabi.newpipe.settings.preferencesearch.PreferenceSearchItem
import org.xmlpull.v1.XmlPullParser
import org.schabi.newpipe.settings.preferencesearch.PreferenceParser
import org.schabi.newpipe.settings.preferencesearch.PreferenceSearchAdapter.PreferenceCallback
import androidx.recyclerview.widget.DiffUtil
import org.schabi.newpipe.settings.preferencesearch.PreferenceSearcher
import org.schabi.newpipe.settings.preferencesearch.PreferenceSearchAdapter
import org.schabi.newpipe.settings.preferencesearch.PreferenceSearchResultListener
import org.schabi.newpipe.settings.preferencesearch.PreferenceSearchFragment
import org.schabi.newpipe.settings.preferencesearch.PreferenceSearchConfiguration.PreferenceSearchFunction
import org.schabi.newpipe.settings.preferencesearch.PreferenceFuzzySearchFunction.FuzzySearchGeneralDTO
import org.schabi.newpipe.settings.preferencesearch.PreferenceFuzzySearchFunction.FuzzySearchSpecificDTO
import org.schabi.newpipe.settings.preferencesearch.PreferenceFuzzySearchFunction
import org.apache.commons.text.similarity.FuzzyScore
import androidx.preference.PreferenceFragmentCompat
import org.schabi.newpipe.settings.preferencesearch.PreferenceSearchResultHighlighter
import androidx.preference.PreferenceGroup.PreferencePositionCallback
import android.graphics.drawable.RippleDrawable
import android.content.res.Resources.Theme
import android.content.res.TypedArray
import org.schabi.newpipe.settings.SettingMigrations
import org.schabi.newpipe.settings.MainSettingsFragment
import org.schabi.newpipe.settings.SettingsResourceRegistry
import org.schabi.newpipe.settings.SettingsResourceRegistry.SettingRegistryEntry
import org.schabi.newpipe.util.ReleaseVersionUtil
import org.schabi.newpipe.util.KeyboardUtil
import org.schabi.newpipe.settings.SelectKioskFragment.SelectKioskAdapter
import org.schabi.newpipe.settings.SelectKioskFragment.SelectKioskAdapter.SelectKioskItemHolder
import org.schabi.newpipe.settings.BasePreferenceFragment
import org.schabi.newpipe.settings.DebugSettingsFragment.DebugSettingsBVDLeakCanaryAPI
import org.schabi.newpipe.local.feed.notifications.NotificationWorker
import org.schabi.newpipe.settings.DebugSettingsFragment
import org.schabi.newpipe.settings.SelectChannelFragment.SelectChannelAdapter
import org.schabi.newpipe.settings.SelectChannelFragment.SelectChannelAdapter.SelectChannelItemHolder
import org.schabi.newpipe.settings.SelectPlaylistFragment.SelectPlaylistAdapter
import org.schabi.newpipe.settings.SelectPlaylistFragment.SelectPlaylistAdapter.SelectPlaylistItemHolder
import org.schabi.newpipe.NewVersionWorker
import org.schabi.newpipe.settings.UpdateSettingsFragment
import androidx.preference.SwitchPreferenceCompat
import org.schabi.newpipe.settings.DownloadSettingsFragment
import org.schabi.newpipe.settings.AppearanceSettingsFragment
import org.schabi.newpipe.settings.ContentSettingsFragment
import org.schabi.newpipe.settings.NotificationSettingsFragment
import org.schabi.newpipe.settings.PlayerNotificationSettingsFragment
import org.schabi.newpipe.settings.VideoAudioSettingsFragment
import org.schabi.newpipe.settings.ExoPlayerSettingsFragment
import org.schabi.newpipe.settings.BackupRestoreSettingsFragment
import android.text.format.DateUtils
import android.content.res.Resources.NotFoundException
import org.schabi.newpipe.settings.PeertubeInstanceListFragment.InstanceListAdapter
import org.schabi.newpipe.settings.PeertubeInstanceListFragment.PeertubeInstanceCallback
import org.schabi.newpipe.settings.ContentSettingsManager
import org.schabi.newpipe.settings.NewPipeFileLocator
import org.schabi.newpipe.fragments.list.BaseListInfoFragment
import org.schabi.newpipe.extractor.services.media_ccc.extractors.MediaCCCLiveStreamKiosk
import org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory
import org.schabi.newpipe.extractor.kiosk.KioskList
import org.schabi.newpipe.fragments.list.BaseListFragment
import org.schabi.newpipe.fragments.BackPressable
import org.schabi.newpipe.fragments.list.search.SuggestionListAdapter
import android.text.TextWatcher
import org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeSearchQueryHandlerFactory
import org.schabi.newpipe.extractor.services.peertube.linkHandler.PeertubeSearchQueryHandlerFactory
import androidx.appcompat.widget.TooltipCompat
import android.view.View.OnFocusChangeListener
import org.schabi.newpipe.fragments.list.search.SuggestionListAdapter.OnSuggestionItemSelected
import org.schabi.newpipe.fragments.list.search.SuggestionItem
import android.text.style.CharacterStyle
import android.widget.TextView.OnEditorActionListener
import android.view.inputmethod.EditorInfo
import io.reactivex.rxjava3.core.ObservableSource
import org.schabi.newpipe.extractor.search.SearchExtractor.NothingFoundException
import android.text.Html
import org.schabi.newpipe.fragments.list.search.SuggestionListAdapter.SuggestionItemHolder
import org.schabi.newpipe.fragments.list.search.SuggestionListAdapter.SuggestionItemCallback
import org.schabi.newpipe.fragments.list.videos.RelatedItemsInfo
import org.schabi.newpipe.fragments.list.videos.RelatedItemsFragment
import org.schabi.newpipe.local.feed.notifications.NotificationHelper
import org.schabi.newpipe.fragments.list.channel.ChannelTabFragment
import org.schabi.newpipe.fragments.list.channel.ChannelAboutFragment
import org.schabi.newpipe.extractor.exceptions.ContentNotSupportedException
import org.schabi.newpipe.extractor.linkhandler.ReadyChannelTabListLinkHandler
import org.schabi.newpipe.player.playqueue.ChannelTabPlayQueue
import org.schabi.newpipe.fragments.detail.BaseDescriptionFragment
import org.schabi.newpipe.extractor.stream.StreamExtractor
import org.schabi.newpipe.fragments.list.comments.CommentsFragment
import org.schabi.newpipe.fragments.list.comments.CommentRepliesInfo
import androidx.constraintlayout.widget.ConstraintLayout
import com.google.android.material.shape.ShapeAppearanceModel
import com.google.android.material.shape.CornerFamily
import org.schabi.newpipe.player.playqueue.PlaylistPlayQueue
import org.schabi.newpipe.info_list.InfoListAdapter
import org.schabi.newpipe.views.SuperScrollLayoutManager
import org.schabi.newpipe.extractor.playlist.PlaylistInfoItem
import org.schabi.newpipe.fragments.list.BaseListFragment.DefaultItemListOnScrolledDownListener
import org.schabi.newpipe.fragments.ViewContract
import androidx.fragment.app.FragmentPagerAdapter
import org.schabi.newpipe.extractor.stream.StreamExtractor.Privacy
import org.schabi.newpipe.player.event.OnKeyDownListener
import com.google.android.material.bottomsheet.BottomSheetBehavior.BottomSheetCallback
import android.content.pm.ActivityInfo
import org.schabi.newpipe.fragments.detail.VideoDetailPlayerCrasher
import com.google.android.material.appbar.AppBarLayout.OnOffsetChangedListener
import org.schabi.newpipe.fragments.EmptyFragment
import org.schabi.newpipe.fragments.detail.DescriptionFragment
import org.schabi.newpipe.extractor.StreamingService.ServiceInfo.MediaCapability
import android.text.style.StyleSpan
import android.graphics.Typeface
import com.google.android.material.chip.Chip
import com.google.android.exoplayer2.ExoPlaybackException
import com.google.android.material.tabs.TabLayout.OnTabSelectedListener
import androidx.viewpager.widget.ViewPager
import androidx.annotation.ColorInt
import androidx.recyclerview.widget.StaggeredGridLayoutManager
import org.schabi.newpipe.info_list.dialog.StreamDialogEntry
import org.schabi.newpipe.info_list.dialog.InfoItemDialog
import org.schabi.newpipe.info_list.InfoItemBuilder
import org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder
import org.schabi.newpipe.info_list.holder.ChannelMiniInfoItemHolder
import org.schabi.newpipe.info_list.holder.InfoItemHolder
import org.schabi.newpipe.info_list.holder.CommentInfoItemHolder
import org.schabi.newpipe.info_list.holder.PlaylistMiniInfoItemHolder
import org.schabi.newpipe.info_list.holder.StreamInfoItemHolder
import org.schabi.newpipe.extractor.InfoItem.InfoType
import org.schabi.newpipe.info_list.holder.ChannelInfoItemHolder
import org.schabi.newpipe.info_list.holder.PlaylistInfoItemHolder
import org.schabi.newpipe.info_list.holder.StreamGridInfoItemHolder
import org.schabi.newpipe.info_list.holder.StreamCardInfoItemHolder
import org.schabi.newpipe.info_list.holder.ChannelCardInfoItemHolder
import org.schabi.newpipe.info_list.holder.ChannelGridInfoItemHolder
import org.schabi.newpipe.info_list.holder.PlaylistGridInfoItemHolder
import org.schabi.newpipe.info_list.holder.PlaylistCardInfoItemHolder
import org.schabi.newpipe.ExitActivity
import androidx.appcompat.app.ActionBarDrawerToggle
import androidx.drawerlayout.widget.DrawerLayout.SimpleDrawerListener
import com.google.android.material.navigation.NavigationView
import android.widget.ArrayAdapter
import androidx.core.view.GravityCompat
import androidx.fragment.app.FragmentContainerView
import org.schabi.newpipe.extractor.exceptions.ReCaptchaException
import okhttp3.RequestBody
import okhttp3.ResponseBody
import org.schabi.newpipe.RouterActivity.ChoiceAvailabilityChecker
import org.schabi.newpipe.RouterActivity.AdapterChoiceItem
import android.content.DialogInterface.OnShowListener
import org.schabi.newpipe.RouterActivity.FetcherService
import androidx.lifecycle.DefaultLifecycleObserver
import androidx.lifecycle.LifecycleOwner
import io.reactivex.rxjava3.core.SingleOnSubscribe
import io.reactivex.rxjava3.core.SingleEmitter
import io.reactivex.rxjava3.core.SingleTransformer
import org.schabi.newpipe.RouterActivity.PersistentFragment
import android.app.IntentService
import org.schabi.newpipe.util.urlfinder.UrlFinder
import org.schabi.newpipe.extractor.exceptions.AgeRestrictedContentException
import org.schabi.newpipe.extractor.exceptions.GeographicRestrictionException
import org.schabi.newpipe.extractor.exceptions.PaidContentException
import org.schabi.newpipe.extractor.exceptions.PrivateContentException
import org.schabi.newpipe.extractor.exceptions.SoundCloudGoPlusContentException
import org.schabi.newpipe.extractor.exceptions.YoutubeMusicPremiumContentException
import org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException
import kotlin.concurrent.Volatile
import org.schabi.newpipe.PanicResponderActivity
import android.os.ParcelFileDescriptor
import us.shandian.giga.io.CircularFileWriter.OffsetChecker
import us.shandian.giga.io.ProgressReport
import us.shandian.giga.io.CircularFileWriter.WriteErrorHandle
import us.shandian.giga.io.CircularFileWriter.BufferedFile
import us.shandian.giga.io.CircularFileWriter
import us.shandian.giga.io.ChunkFileInputStream
import us.shandian.giga.ui.adapter.MissionAdapter
import us.shandian.giga.service.DownloadManager.MissionIterator
import us.shandian.giga.get.Mission
import us.shandian.giga.ui.common.Deleter
import androidx.core.os.HandlerCompat
import us.shandian.giga.get.FinishedMission
import us.shandian.giga.ui.common.ProgressDrawable
import us.shandian.giga.ui.adapter.MissionAdapter.ViewHolderItem
import us.shandian.giga.ui.adapter.MissionAdapter.RecoverHelper
import us.shandian.giga.ui.adapter.MissionAdapter.ViewHolderHeader
import us.shandian.giga.get.DownloadMission
import us.shandian.giga.service.DownloadManager.MissionItem
import android.app.NotificationManager
import android.view.HapticFeedbackConstants
import android.webkit.MimeTypeMap
import android.database.sqlite.SQLiteOpenHelper
import us.shandian.giga.get.sqlite.FinishedMissionStore
import android.database.sqlite.SQLiteDatabase
import android.content.ContentValues
import android.system.ErrnoException
import android.system.OsConstants
import us.shandian.giga.get.DownloadRunnableFallback
import us.shandian.giga.get.DownloadRunnable
import us.shandian.giga.get.DownloadInitializer
import us.shandian.giga.get.DownloadMissionRecover
import android.os.StatFs
import okio.ByteString
import org.schabi.newpipe.player.helper.LockManager
import android.graphics.BitmapFactory
import android.net.NetworkRequest
import android.net.NetworkInfo
import us.shandian.giga.postprocessing.TtmlConverter
import us.shandian.giga.postprocessing.WebMMuxer
import us.shandian.giga.postprocessing.Mp4FromDashMuxer
import us.shandian.giga.postprocessing.M4aNoDash
import us.shandian.giga.postprocessing.OggFromWebmDemuxer
