/*
 * SPDX-FileCopyrightText: 2026 NewPipe e.V. <https://newpipe-ev.de>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package net.newpipe.app.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Classes to hold information parsed from the BOM generated by the AboutLibraries plugin
 */
@Serializable
data class AboutLibraries(
    val libraries: List<Library>
)

@Serializable
data class Library(
    @SerialName("uniqueId")
    val id: String,
    val name: String,
    val developers: List<Developer>,
    val licenses: List<String>,
    val website: String? = null
)

@Serializable
data class Developer(
    val name: String,
    val organisationUrl: String? = null
)
