/*
 * SPDX-FileCopyrightText: 2026 NewPipe e.V. <https://newpipe-ev.de>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

const val NEWPIPE_VERSION_SDK_COMPILE_MAJOR = 36
const val NEWPIPE_VERSION_SDK_COMPILE_MINOR = 1
const val NEWPIPE_VERSION_SDK_MIN = 23
const val NEWPIPE_VERSION_SDK_TARGET = 35

const val NEWPIPE_VERSION_CODE = 1012
const val NEWPIPE_VERSION_NAME = "0.28.7"

const val NEWPIPE_MATERIAL_RELEASE_NUMBER = 3
const val NEWPIPE_MATERIAL_VERSION_NAME = "${NEWPIPE_VERSION_NAME}-m$NEWPIPE_MATERIAL_RELEASE_NUMBER"
const val NEWPIPE_MATERIAL_VERSION_CODE = NEWPIPE_VERSION_CODE * 100 + NEWPIPE_MATERIAL_RELEASE_NUMBER

const val NEWPIPE_APPLICATION_ID_OLD = "org.schabi.newpipe"
const val NEWPIPE_APPLICATION_ID_NEW = "net.newpipe.app"
const val NEWPIPE_MATERIAL_APPLICATION_ID = "org.wisso.newpipematerial"
