package org.schabi.newpipe.database.subscription;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;

import static org.schabi.newpipe.database.subscription.SubscriptionEntity.CHANNEL_SERVICE_ID;
import static org.schabi.newpipe.database.subscription.SubscriptionEntity.CHANNEL_TABLE;
import static org.schabi.newpipe.database.subscription.SubscriptionEntity.CHANNEL_URL;

@Entity(tableName = CHANNEL_TABLE,
        indices = {@Index(value = {CHANNEL_SERVICE_ID, CHANNEL_URL}, unique = true)})
public class SubscriptionEntity {

    final static String CHANNEL_TABLE                   = "channel";
    final static String CHANNEL_SERVICE_ID              = "service_id";
    final static String CHANNEL_URL                     = "url";
    final static String CHANNEL_LATEST_STREAM_URL       = "latest_stream_url";
    final static String CHANNEL_LATEST_STREAM_VIEWED    = "latest_stream_viewed";

    @PrimaryKey(autoGenerate = true)
    private long uid = 0;

    @ColumnInfo(name = CHANNEL_SERVICE_ID)
    private int serviceId = -1;

    /* Do not keep extraneous information on entities as they are dynamic */
    @ColumnInfo(name = CHANNEL_URL)
    private String url;

    @ColumnInfo(name = CHANNEL_LATEST_STREAM_URL)
    private String latestStreamUrl;

    @ColumnInfo(name = CHANNEL_LATEST_STREAM_VIEWED)
    private boolean latestStreamViewed;

    public long getUid() {
        return uid;
    }

    /* Keep this package-private since UID should always be auto generated by Room impl */
    void setUid(long uid) {
        this.uid = uid;
    }

    public int getServiceId() {
        return serviceId;
    }

    public void setServiceId(int serviceId) {
        this.serviceId = serviceId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getLatestStreamUrl() {
        return latestStreamUrl;
    }

    public void setLatestStreamUrl(String latestStreamUrl) {
        this.latestStreamUrl = latestStreamUrl;
    }

    public boolean isLatestStreamViewed() {
        return latestStreamViewed;
    }

    public void setLatestStreamViewed(boolean latestStreamViewed) {
        this.latestStreamViewed = latestStreamViewed;
    }
}
