@file:OptIn(androidx.media3.common.util.UnstableApi::class)

package org.schabi.newpipe.player.helper

import android.annotation.SuppressLint
import android.content.Context
import android.content.SharedPreferences
import android.content.pm.PackageManager
import android.provider.Settings
import android.view.accessibility.CaptioningManager
import androidx.annotation.IntDef
import androidx.core.content.ContextCompat
import androidx.preference.PreferenceManager
import androidx.media3.common.PlaybackParameters
import androidx.media3.exoplayer.SeekParameters
import androidx.media3.exoplayer.source.ProgressiveMediaSource
import androidx.media3.exoplayer.trackselection.AdaptiveTrackSelection
import androidx.media3.exoplayer.trackselection.ExoTrackSelection
import androidx.media3.ui.AspectRatioFrameLayout
import androidx.media3.ui.CaptionStyleCompat
import java.text.DecimalFormat
import java.text.DecimalFormatSymbols
import java.text.NumberFormat
import java.util.Locale
import java.util.concurrent.TimeUnit
import org.schabi.newpipe.R
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.utils.Utils
import org.schabi.newpipe.player.Player
import org.schabi.newpipe.player.playqueue.PlayQueue
import org.schabi.newpipe.player.playqueue.PlayQueueItem
import org.schabi.newpipe.player.playqueue.SinglePlayQueue
import org.schabi.newpipe.util.ListHelper
import org.schabi.newpipe.util.Localization

object PlayerHelper {
    private val FORMATTERS_PROVIDER = FormattersProvider()

    @Retention(AnnotationRetention.SOURCE)
    @IntDef(AUTOPLAY_TYPE_ALWAYS, AUTOPLAY_TYPE_WIFI, AUTOPLAY_TYPE_NEVER)
    annotation class AutoplayType

    const val AUTOPLAY_TYPE_ALWAYS = 0
    const val AUTOPLAY_TYPE_WIFI = 1
    const val AUTOPLAY_TYPE_NEVER = 2

    @Retention(AnnotationRetention.SOURCE)
    @IntDef(MINIMIZE_ON_EXIT_MODE_NONE, MINIMIZE_ON_EXIT_MODE_BACKGROUND, MINIMIZE_ON_EXIT_MODE_POPUP)
    annotation class MinimizeMode

    const val MINIMIZE_ON_EXIT_MODE_NONE = 0
    const val MINIMIZE_ON_EXIT_MODE_BACKGROUND = 1
    const val MINIMIZE_ON_EXIT_MODE_POPUP = 2

    @JvmStatic
    fun resetFormat() {
        FORMATTERS_PROVIDER.reset()
    }

    @JvmStatic
    fun getTimeString(milliSeconds: Long): String {
        val seconds = (milliSeconds % 60000) / 1000
        val minutes = (milliSeconds % 3600000) / 60000
        val hours = (milliSeconds % 86400000) / 3600000
        val days = (milliSeconds % (86400000 * 7)) / 86400000

        val formatters = FORMATTERS_PROVIDER.formatters()
        return if (days > 0) {
            formatters.stringFormat("%d:%02d:%02d:%02d", days, hours, minutes, seconds)
        } else if (hours > 0) {
            formatters.stringFormat("%d:%02d:%02d", hours, minutes, seconds)
        } else {
            formatters.stringFormat("%02d:%02d", minutes, seconds)
        }
    }

    @JvmStatic
    fun formatSpeed(speed: Double): String {
        return FORMATTERS_PROVIDER.formatters().speed.format(speed)
    }

    @JvmStatic
    fun formatPitch(pitch: Double): String {
        return FORMATTERS_PROVIDER.formatters().pitch.format(pitch)
    }

    @JvmStatic
    fun captionLanguageOf(context: Context, subtitles: SubtitlesStream): String {
        val displayName = subtitles.displayLanguageName
        return displayName + (if (subtitles.isAutoGenerated) " (" + context.getString(R.string.caption_auto_generated) + ")" else "")
    }

    @JvmStatic
    fun captionLanguageStemOf(language: String): String {
        if (!language.contains("(") || !language.contains(")")) {
            return language
        }

        if (language.startsWith("(")) {
            // language text is right-to-left
            val parts = language.split("\\)".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
            return parts[parts.size - 1].trim { it <= ' ' }
        }

        return language.split("\\(".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()[0].trim { it <= ' ' }
    }

    @JvmStatic
    fun resizeTypeOf(context: Context, resizeMode: Int): String {
        return when (resizeMode) {
            AspectRatioFrameLayout.RESIZE_MODE_FIT -> context.getString(R.string.resize_fit)
            AspectRatioFrameLayout.RESIZE_MODE_FILL -> context.getString(R.string.resize_fill)
            AspectRatioFrameLayout.RESIZE_MODE_ZOOM -> context.getString(R.string.resize_zoom)
            else -> throw IllegalArgumentException("Unrecognized resize mode: $resizeMode")
        }
    }

    @JvmStatic
    fun autoQueueOf(info: StreamInfo, existingItems: List<PlayQueueItem>): PlayQueue? {
        val urls = existingItems.map { it.url }.toSet()

        val relatedItems = info.relatedItems
        if (Utils.isNullOrEmpty(relatedItems)) {
            return null
        }

        if (relatedItems[0] is StreamInfoItem && !urls.contains(relatedItems[0].url)) {
            return getAutoQueuedSinglePlayQueue(relatedItems[0] as StreamInfoItem)
        }

        val autoQueueItems = relatedItems
            .filterIsInstance<StreamInfoItem>()
            .filter { !urls.contains(it.url) }
            .shuffled()

        return if (autoQueueItems.isEmpty()) null else getAutoQueuedSinglePlayQueue(autoQueueItems[0])
    }

    @JvmStatic
    fun isResumeAfterAudioFocusGain(context: Context): Boolean {
        return getPreferences(context).getBoolean(context.getString(R.string.resume_on_audio_focus_gain_key), false)
    }

    @JvmStatic
    fun getActionForRightGestureSide(context: Context): String? {
        return getPreferences(context).getString(
            context.getString(R.string.right_gesture_control_key),
            context.getString(R.string.default_right_gesture_control_value)
        )
    }

    @JvmStatic
    fun getActionForLeftGestureSide(context: Context): String? {
        return getPreferences(context).getString(
            context.getString(R.string.left_gesture_control_key),
            context.getString(R.string.default_left_gesture_control_value)
        )
    }

    @JvmStatic
    fun isStartMainPlayerFullscreenEnabled(context: Context): Boolean {
        return getPreferences(context).getBoolean(context.getString(R.string.start_main_player_fullscreen_key), false)
    }

    @JvmStatic
    fun isAutoQueueEnabled(context: Context): Boolean {
        return getPreferences(context).getBoolean(context.getString(R.string.auto_queue_key), false)
    }

    @JvmStatic
    fun isClearingQueueConfirmationRequired(context: Context): Boolean {
        return getPreferences(context).getBoolean(context.getString(R.string.clear_queue_confirmation_key), false)
    }

    @JvmStatic
    @MinimizeMode
    fun getMinimizeOnExitAction(context: Context): Int {
        val action = getPreferences(context).getString(context.getString(R.string.minimize_on_exit_key), "")
        return when (action) {
            context.getString(R.string.minimize_on_exit_popup_key) -> MINIMIZE_ON_EXIT_MODE_POPUP
            context.getString(R.string.minimize_on_exit_none_key) -> MINIMIZE_ON_EXIT_MODE_NONE
            else -> MINIMIZE_ON_EXIT_MODE_BACKGROUND // default
        }
    }

    @JvmStatic
    @AutoplayType
    fun getAutoplayType(context: Context): Int {
        val type = getPreferences(context).getString(context.getString(R.string.autoplay_key), "")
        return when (type) {
            context.getString(R.string.autoplay_always_key) -> AUTOPLAY_TYPE_ALWAYS
            context.getString(R.string.autoplay_never_key) -> AUTOPLAY_TYPE_NEVER
            else -> AUTOPLAY_TYPE_WIFI // default
        }
    }

    @JvmStatic
    fun isAutoplayAllowedByUser(context: Context): Boolean {
        return when (getAutoplayType(context)) {
            AUTOPLAY_TYPE_NEVER -> false
            AUTOPLAY_TYPE_WIFI -> !ListHelper.isMeteredNetwork(context)
            AUTOPLAY_TYPE_ALWAYS -> true
            else -> true
        }
    }

    @JvmStatic
    fun getSeekParameters(context: Context): SeekParameters {
        return if (isUsingInexactSeek(context)) SeekParameters.CLOSEST_SYNC else SeekParameters.EXACT
    }

    @JvmStatic
    fun getPreferredCacheSize(): Long {
        return 64 * 1024 * 1024L
    }

    @JvmStatic
    fun getPreferredFileSize(): Long {
        return 2 * 1024 * 1024L // ExoPlayer CacheDataSink.MIN_RECOMMENDED_FRAGMENT_SIZE
    }

    @JvmStatic
    fun getQualitySelector(): ExoTrackSelection.Factory {
        return AdaptiveTrackSelection.Factory(
            1000,
            AdaptiveTrackSelection.DEFAULT_MAX_DURATION_FOR_QUALITY_DECREASE_MS,
            AdaptiveTrackSelection.DEFAULT_MIN_DURATION_TO_RETAIN_AFTER_DISCARD_MS,
            AdaptiveTrackSelection.DEFAULT_BANDWIDTH_FRACTION
        )
    }

    @JvmStatic
    fun getCaptionStyle(context: Context): CaptionStyleCompat {
        val captioningManager = ContextCompat.getSystemService(context, CaptioningManager::class.java)
        return if (captioningManager == null || !captioningManager.isEnabled) {
            CaptionStyleCompat.DEFAULT
        } else {
            CaptionStyleCompat.createFromCaptionStyle(captioningManager.userStyle)
        }
    }

    @JvmStatic
    fun getCaptionScale(context: Context): Float {
        val captioningManager = ContextCompat.getSystemService(context, CaptioningManager::class.java)
        return if (captioningManager == null || !captioningManager.isEnabled) {
            1.0f
        } else {
            captioningManager.fontScale
        }
    }

    @JvmStatic
    fun getScreenBrightness(context: Context): Float {
        val sp = getPreferences(context)
        val timestamp = sp.getLong(context.getString(R.string.screen_brightness_timestamp_key), 0)
        return if (System.currentTimeMillis() - timestamp > TimeUnit.HOURS.toMillis(4)) {
            -1f
        } else {
            sp.getFloat(context.getString(R.string.screen_brightness_key), -1f)
        }
    }

    @JvmStatic
    fun setScreenBrightness(context: Context, screenBrightness: Float) {
        getPreferences(context).edit()
            .putFloat(context.getString(R.string.screen_brightness_key), screenBrightness)
            .putLong(context.getString(R.string.screen_brightness_timestamp_key), System.currentTimeMillis())
            .apply()
    }

    @JvmStatic
    fun globalScreenOrientationLocked(context: Context): Boolean {
        return try {
            Settings.System.getInt(context.contentResolver, Settings.System.ACCELEROMETER_ROTATION, 0) == 0 ||
                !context.packageManager.hasSystemFeature(PackageManager.FEATURE_SENSOR_ACCELEROMETER)
        } catch (e: Exception) {
            false
        }
    }

    @JvmStatic
    fun getProgressiveLoadIntervalBytes(context: Context): Int {
        val preferredIntervalBytes = getPreferences(context).getString(
            context.getString(R.string.progressive_load_interval_key),
            context.getString(R.string.progressive_load_interval_default_value)
        )

        if (context.getString(R.string.progressive_load_interval_exoplayer_default_value) == preferredIntervalBytes) {
            return ProgressiveMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES
        }
        return (preferredIntervalBytes?.toInt() ?: 0) * 1024
    }

    private fun getPreferences(context: Context): SharedPreferences {
        return PreferenceManager.getDefaultSharedPreferences(context)
    }

    private fun isUsingInexactSeek(context: Context): Boolean {
        return getPreferences(context).getBoolean(context.getString(R.string.use_inexact_seek_key), false)
    }

    private fun getAutoQueuedSinglePlayQueue(streamInfoItem: StreamInfoItem): SinglePlayQueue {
        val singlePlayQueue = SinglePlayQueue(streamInfoItem)
        checkNotNull(singlePlayQueue.item).isAutoQueued = true
        return singlePlayQueue
    }

    @JvmStatic
    fun retrieveResizeModeFromPrefs(player: Player): Int {
        return player.prefs.getInt(
            player.context.getString(R.string.last_resize_mode),
            AspectRatioFrameLayout.RESIZE_MODE_FIT
        )
    }

    @JvmStatic
    @SuppressLint("SwitchIntDef")
    fun nextResizeModeAndSaveToPrefs(player: Player, resizeMode: Int): Int {
        val newResizeMode = when (resizeMode) {
            AspectRatioFrameLayout.RESIZE_MODE_FIT -> AspectRatioFrameLayout.RESIZE_MODE_FILL
            AspectRatioFrameLayout.RESIZE_MODE_FILL -> AspectRatioFrameLayout.RESIZE_MODE_ZOOM
            AspectRatioFrameLayout.RESIZE_MODE_ZOOM -> AspectRatioFrameLayout.RESIZE_MODE_FIT
            else -> AspectRatioFrameLayout.RESIZE_MODE_FIT
        }

        player.prefs.edit().putInt(player.context.getString(R.string.last_resize_mode), newResizeMode).apply()
        return newResizeMode
    }

    @JvmStatic
    fun retrievePlaybackParametersFromPrefs(player: Player): PlaybackParameters {
        val speed = player.prefs.getFloat(player.context.getString(R.string.playback_speed_key), player.playbackSpeed)
        val pitch = player.prefs.getFloat(player.context.getString(R.string.playback_pitch_key), player.playbackPitch)
        return PlaybackParameters(speed, pitch)
    }

    @JvmStatic
    fun savePlaybackParametersToPrefs(player: Player, speed: Float, pitch: Float, skipSilence: Boolean) {
        player.prefs.edit()
            .putFloat(player.context.getString(R.string.playback_speed_key), speed)
            .putFloat(player.context.getString(R.string.playback_pitch_key), pitch)
            .putBoolean(player.context.getString(R.string.playback_skip_silence_key), skipSilence)
            .apply()
    }

    @JvmStatic
    fun getMinimumVideoHeight(width: Float): Float {
        return width / (16.0f / 9.0f)
    }

    @JvmStatic
    fun retrieveSeekDurationFromPreferences(player: Player): Int {
        return (
            player.prefs.getString(
                player.context.getString(R.string.seek_duration_key),
                player.context.getString(R.string.seek_duration_default_value)
            ) ?: "0"
            ).toInt()
    }

    internal class FormattersProvider {
        private var formatters: Formatters? = null

        fun formatters(): Formatters {
            if (formatters == null) {
                formatters = Formatters.create()
            }
            return formatters!!
        }

        fun reset() {
            formatters = null
        }
    }

    internal data class Formatters(
        val locale: Locale,
        val speed: NumberFormat,
        val pitch: NumberFormat
    ) {
        fun stringFormat(format: String, vararg args: Any?): String {
            return String.format(locale, format, *args)
        }

        companion object {
            fun create(): Formatters {
                val locale = Localization.getAppLocale()
                val dfs = DecimalFormatSymbols.getInstance(locale)
                return Formatters(
                    locale,
                    DecimalFormat("0.##x", dfs),
                    DecimalFormat("##%", dfs)
                )
            }
        }
    }
}
