package org.schabi.newpipe.database.channel;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;

import static org.schabi.newpipe.database.channel.ChannelEntity.CHANNEL_LAST_VIDEO_ID;
import static org.schabi.newpipe.database.channel.ChannelEntity.CHANNEL_SERVICE_ID;
import static org.schabi.newpipe.database.channel.ChannelEntity.CHANNEL_TABLE;
import static org.schabi.newpipe.database.channel.ChannelEntity.CHANNEL_URL;

@Entity(tableName = CHANNEL_TABLE,
        indices = {@Index(value = {CHANNEL_SERVICE_ID, CHANNEL_URL}, unique = true)})
public class ChannelEntity {

    final static String CHANNEL_TABLE       = "channel";
    final static String CHANNEL_SERVICE_ID  = "service_id";
    final static String CHANNEL_URL         = "url";
    final static String CHANNEL_LAST_VIDEO_ID = "last_video_id";
    final static String CHANNEL_LAST_VIDEO_VIEWED = "last_video_viewed";

    @PrimaryKey(autoGenerate = true)
    private long uid = 0;

    @ColumnInfo(name = CHANNEL_SERVICE_ID)
    private int serviceId = -1;

    /* Do not keep extraneous information on entities as they are dynamic */
    @ColumnInfo(name = CHANNEL_URL)
    private String url;

    @ColumnInfo(name = CHANNEL_LAST_VIDEO_ID)
    private String lastVideoId;

    @ColumnInfo(name = CHANNEL_LAST_VIDEO_VIEWED)
    private boolean lastVideoViewed;

    public long getUid() {
        return uid;
    }

    /* Keep this package-private since UID should always be auto generated by Room impl */
    void setUid(long uid) {
        this.uid = uid;
    }

    public int getServiceId() {
        return serviceId;
    }

    public void setServiceId(int serviceId) {
        this.serviceId = serviceId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getLastVideoId() {
        return lastVideoId;
    }

    public void setLastVideoId(String lastVideoId) {
        this.lastVideoId = lastVideoId;
    }

    public boolean isLastVideoViewed() {
        return lastVideoViewed;
    }

    public void setLastVideoViewed(boolean lastVideoViewed) {
        this.lastVideoViewed = lastVideoViewed;
    }
}
