@file:OptIn(androidx.media3.common.util.UnstableApi::class)

package org.schabi.newpipe.player.resolver

import android.content.Context
import android.net.Uri
import android.util.Log
import androidx.media3.common.C
import androidx.media3.common.MediaItem
import androidx.media3.exoplayer.source.MediaSource
import androidx.media3.exoplayer.source.MergingMediaSource
import java.util.Optional
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.VideoStream
import org.schabi.newpipe.player.helper.PlayerDataSource
import org.schabi.newpipe.player.helper.PlayerHelper
import org.schabi.newpipe.player.mediaitem.StreamInfoTag
import org.schabi.newpipe.util.ListHelper
import org.schabi.newpipe.util.ListHelper.getFilteredAudioStreams
import org.schabi.newpipe.util.ListHelper.getPlayableStreams
import org.schabi.newpipe.util.ListHelper.getUrlAndNonTorrentStreams

class VideoPlaybackResolver(
    private val context: Context,
    private val dataSource: PlayerDataSource,
    private val qualityResolver: QualityResolver
) : PlaybackResolver {

    var streamSourceType: SourceType? = null
        private set

    var playbackQuality: String? = null
    var audioTrack: String? = null

    enum class SourceType {
        LIVE_STREAM,
        VIDEO_WITH_SEPARATED_AUDIO,
        VIDEO_WITH_AUDIO_OR_AUDIO_ONLY
    }

    override fun resolve(info: StreamInfo): MediaSource? {
        val liveSource = PlaybackResolver.maybeBuildLiveMediaSource(dataSource, info)
        if (liveSource != null) {
            streamSourceType = SourceType.LIVE_STREAM
            return liveSource
        }

        val mediaSources = mutableListOf<MediaSource>()

        // Create video stream source
        val videoStreamsList = ListHelper.getSortedStreamVideosList(
            context,
            getPlayableStreams(info.videoStreams, info.serviceId),
            getPlayableStreams(info.videoOnlyStreams, info.serviceId),
            false,
            true
        )
        val audioStreamsList = getFilteredAudioStreams(context, info.audioStreams)

        val videoIndex = when {
            videoStreamsList.isEmpty() -> -1
            playbackQuality == null -> qualityResolver.getDefaultResolutionIndex(videoStreamsList)
            else -> qualityResolver.getOverrideResolutionIndex(videoStreamsList, playbackQuality!!)
        }

        val audioIndex = ListHelper.getAudioFormatIndex(context, audioStreamsList, audioTrack)
        val tag = StreamInfoTag.of(info, videoStreamsList, videoIndex, audioStreamsList, audioIndex)
        val video = tag.maybeQuality?.selectedVideoStream
        val audio = tag.maybeAudioTrack?.selectedAudioStream

        if (video != null) {
            try {
                val streamSource = PlaybackResolver.buildMediaSource(
                    dataSource,
                    video,
                    info,
                    PlaybackResolver.cacheKeyOf(info, video),
                    tag
                )
                mediaSources.add(streamSource)
            } catch (e: PlaybackResolver.ResolverException) {
                Log.e(TAG, "Unable to create video source", e)
                return null
            }
        }

        // Use the audio stream if there is no video stream, or
        // merge with audio stream in case if video does not contain audio
        if (audio != null && (video == null || video.isVideoOnly || audioTrack != null)) {
            try {
                val audioSource = PlaybackResolver.buildMediaSource(
                    dataSource,
                    audio,
                    info,
                    PlaybackResolver.cacheKeyOf(info, audio),
                    tag
                )
                mediaSources.add(audioSource)
                streamSourceType = SourceType.VIDEO_WITH_SEPARATED_AUDIO
            } catch (e: PlaybackResolver.ResolverException) {
                Log.e(TAG, "Unable to create audio source", e)
                return null
            }
        } else {
            streamSourceType = SourceType.VIDEO_WITH_AUDIO_OR_AUDIO_ONLY
        }

        // If there is no audio or video sources, then this media source cannot be played back
        if (mediaSources.isEmpty()) {
            return null
        }

        // Below are auxiliary media sources

        // Create subtitle sources
        val subtitlesStreams = info.subtitles
        if (subtitlesStreams != null) {
            // Torrent and non URL subtitles are not supported by ExoPlayer
            val nonTorrentAndUrlStreams = getUrlAndNonTorrentStreams(subtitlesStreams)
            for (subtitle in nonTorrentAndUrlStreams) {
                val mediaFormat = subtitle.format
                if (mediaFormat != null) {
                    val textRoleFlag = if (subtitle.isAutoGenerated) {
                        C.ROLE_FLAG_DESCRIBES_MUSIC_AND_SOUND
                    } else {
                        C.ROLE_FLAG_CAPTION
                    }
                    val textMediaItem = MediaItem.SubtitleConfiguration.Builder(
                        Uri.parse(subtitle.content)
                    )
                        .setMimeType(mediaFormat.mimeType)
                        .setRoleFlags(textRoleFlag)
                        .setLanguage(PlayerHelper.captionLanguageOf(context, subtitle))
                        .build()
                    val textSource = dataSource.singleSampleMediaSourceFactory
                        .createMediaSource(textMediaItem, C.TIME_UNSET)
                    mediaSources.add(textSource)
                }
            }
        }

        return if (mediaSources.size == 1) {
            mediaSources[0]
        } else {
            MergingMediaSource(true, *mediaSources.toTypedArray())
        }
    }

    /**
     * Returns the last resolved [StreamInfo]'s [SourceType].
     *
     * @return [Optional.empty] if nothing was resolved, otherwise the [SourceType]
     * of the last resolved [StreamInfo] inside an [Optional]
     */
    fun getStreamSourceType(): Optional<SourceType> {
        return Optional.ofNullable(streamSourceType)
    }

    interface QualityResolver {
        fun getDefaultResolutionIndex(sortedVideos: List<VideoStream>): Int
        fun getOverrideResolutionIndex(sortedVideos: List<VideoStream>, playbackQuality: String): Int
    }

    companion object {
        private val TAG = VideoPlaybackResolver::class.java.simpleName
    }
}
