name: Build APK

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Rename APK
        run: |
          VERSION_NAME=$(jq -r ".elements[0].versionName" "app/build/outputs/apk/release/output-metadata.json")
          mv app/build/outputs/apk/release/*.apk "app/build/outputs/apk/release/NewPipe_v${VERSION_NAME}.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NewPipe-APK
          path: app/build/outputs/apk/release/*.apk
